#!/usr/bin/env python3

# Copyright (c) 2026, Team SOBITS
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the copyright holder nor the names of its
#   contributors may be used to endorse or promote products derived from this
#   software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

"""
Multi-camera ros2bag to LeRobot dataset conversion.

Operates as a ROS 2 Node, loading config from the recorded_bags_meta.yaml
generated by the sobits_vla_rosbag_collection package.
"""

import os
from pathlib import Path

import rclpy
from rclpy.node import Node
from sobits_vla_common import runtime_deps
from sobits_vla_common.lerobot_compat import apply_conversion_patches
from sobits_vla_common.param_schema import declare_from_schema, P, read_schema
from sobits_vla_rosbag_conversion.dataset_writer import DatasetWriter
from sobits_vla_rosbag_conversion.frame_synthesizer import FrameSynthesizer
from sobits_vla_rosbag_conversion.pipeline.discovery import candidate_bag_dirs, discover_episodes
from sobits_vla_rosbag_conversion.pipeline.episode_pipeline import EpisodePipeline
from sobits_vla_rosbag_conversion.pipeline.stats import episode_stat_dict
from sobits_vla_rosbag_conversion.pipeline.validator import (
    morphologies_match, resolve_cameras, sensors_match,
)
import yaml


runtime_deps.ensure({
    'rosbags': 'pip install rosbags',
    'lerobot': 'pip install lerobot[training]~=0.6.0',
    'pandas': 'pip install pandas',
    'pyarrow': 'pip install pyarrow',
})

apply_conversion_patches()


def _default_output_root() -> Path:
    """
    Resolve the default dataset output root: <package_src>/lerobotdataset/.

    Works from the colcon install space (regular-copy installs) by walking up
    to the workspace root and locating the package under src/, and from
    source/symlink-install runs by finding the package root directly. Falls
    back to the installed share directory if the source tree can't be found.
    """
    candidate = Path(os.path.realpath(__file__)).parent
    for _ in range(8):
        # Source tree (or --symlink-install): package root has package.xml + lerobotdataset/.
        if (candidate / 'package.xml').exists() and (candidate / 'lerobotdataset').is_dir():
            return candidate / 'lerobotdataset'
        # Install space: walk up to workspace root, find package under src/.
        src_root = candidate / 'src'
        if src_root.is_dir():
            for pattern in ('*/sobits_vla_rosbag_conversion', '*/*/sobits_vla_rosbag_conversion'):
                for pkg_dir in src_root.glob(pattern):
                    if (pkg_dir / 'lerobotdataset').is_dir():
                        return pkg_dir / 'lerobotdataset'
        candidate = candidate.parent

    from ament_index_python.packages import get_package_share_directory
    return Path(get_package_share_directory('sobits_vla_rosbag_conversion')) / 'lerobotdataset'


# Static-name declares only; none in this file use a ParameterDescriptor or
# a name built from another param's value, so every declare fits plainly.
_SCHEMA = {
    'rosbag_directory': P(''),
    'recorded_bags_meta_file': P(''),
    'dataset_name': P('MyDataset'),
    'output_directory': P(''),
    'fps': P(10),
    'vcodec': P('auto'),
    'sync_threshold': P(0.1),
    'downsample_tolerance': P(0.015),
    'push_to_hub': P(False),
    'hub_private': P(False),
    'overwrite': P(False),
    'use_relative_actions': P(False),
    'skip_static_threshold': P(0.0),
    # Per-config trim of the shared robot descriptor.
    'exclude': {
        'groups': P(['']),
        'cameras': P(['']),
        'ee_poses': P(['']),
    },
    'cameras': {
        'primary': P(''),
    },
    'robot_descriptor_id': P(''),
}


def _build_camera_maps(sensors: dict):
    """Flat per-camera raw/compressed/info topic + properties maps from all sensor types."""
    sensor_types = sensors.get('types', [])
    all_cam_raw, all_cam_compressed, all_cam_info, all_cam_props = {}, {}, {}, {}
    for stype in sensor_types:
        sdata = sensors.get(stype, {})
        names = sdata.get('names', [])
        topics = sdata.get('topics', [])
        compressed_topics = sdata.get('compressed_topics', [])
        info_topics = sdata.get('info_topics', [])
        props = sdata.get('properties', {})
        for i, name in enumerate(names):
            if i < len(topics) and topics[i]:
                all_cam_raw[name] = topics[i]
            if i < len(compressed_topics) and compressed_topics[i]:
                all_cam_compressed[name] = compressed_topics[i]
            if i < len(info_topics) and info_topics[i]:
                all_cam_info[name] = info_topics[i]
            all_cam_props[name] = props.get(name, {})
    if not all_cam_raw and not all_cam_compressed:
        return None
    return all_cam_raw, all_cam_compressed, all_cam_info, all_cam_props


class RosbagConversionNode(Node):
    def __init__(self):
        super().__init__('rosbag_conversion_node')

        from sobits_vla_common.lerobot_adapter import describe
        seam = describe()
        self.get_logger().info(
            f'lerobot seam: version={seam["version"]} is_v06={seam["is_v06"]} '
            f'unresolvable={seam["unresolvable"]}'
        )

        # Suppress verbose SVT-AV1 encoder logs from PyAV/FFmpeg workers.
        os.environ.setdefault('SVT_LOG', '1')

        declare_from_schema(self, _SCHEMA)
        params = read_schema(self, _SCHEMA)

        self.rosbag_directory = params.rosbag_directory
        self.recorded_bags_meta_file = params.recorded_bags_meta_file
        self.dataset_name = params.dataset_name
        output_dir = params.output_directory
        # Dataset root is <base>/<dataset_name>, <base> = output_directory or
        # <package_src>/lerobotdataset/, so several datasets can share one output_directory.
        if output_dir:
            self.output_directory = Path(output_dir) / self.dataset_name
        else:
            self.output_directory = (
                _default_output_root() / self.dataset_name
            )
            self.get_logger().info(
                f'output_directory not set — defaulting to {self.output_directory}'
            )
        self.fps = params.fps
        self.vcodec = params.vcodec
        self.sync_threshold = params.sync_threshold
        self.downsample_tolerance = params.downsample_tolerance
        self.push_to_hub = params.push_to_hub
        self.hub_private = params.hub_private
        self.overwrite = params.overwrite
        self.use_relative_actions = params.use_relative_actions
        self.skip_static_threshold = params.skip_static_threshold
        self.robot_descriptor_id = params.robot_descriptor_id

        if not self.robot_descriptor_id:
            raise RuntimeError(
                'robot_descriptor_id is required: set it to a descriptor in '
                'sobits_vla_common/robots/<id>.robot.yaml.'
            )

        from sobits_vla_common.robot_descriptor import load_robot_descriptor
        desc = load_robot_descriptor(self.robot_descriptor_id)

        # Per-config trim of the shared descriptor (e.g. left-arm-only runs),
        # so the descriptor keeps describing the whole robot.
        desc = desc.filtered(
            exclude_groups=params.exclude.groups,
            exclude_cameras=params.exclude.cameras,
            exclude_ee_poses=params.exclude.ee_poses,
        )

        # Excluded joints (mimics/inactive groups still listed with active: false)
        self.excluded_joints = desc.all_excluded_ros_names
        # Catches groups omitted entirely, which all_excluded_ros_names above misses.
        self.active_ros_names = set(desc.active_ros_names)

        # Driven purely by exclude.ee_poses: emitted when any frame survives,
        # skipped when all are excluded.
        if desc.ee_poses:
            self.ee_pose_enabled = True
            self.ee_configs = [
                (ee.name, ee.source_frame, ee.target_frame)
                for ee in desc.ee_poses
            ]
        else:
            self.ee_pose_enabled = False
            self.ee_configs = []

        # Cameras. Exclude every camera name for a state/action-only dataset.
        self.skip_cameras = False
        active_cams = desc.active_cameras
        if active_cams:
            self.cameras_names = [c.name for c in active_cams]
            self.cameras_compressed = [c.compressed for c in active_cams]
            primary_param = params.cameras.primary
            if not primary_param:
                self.primary_camera = active_cams[0].name
            else:
                self.primary_camera = primary_param
        else:
            self.cameras_names = []
            self.cameras_compressed = []
            self.skip_cameras = True

        # Depth cameras (parallel tracking, never merged with RGB above)
        active_depth_cams = desc.active_depth_cameras
        self.depth_cameras_names = [c.name for c in active_depth_cams]
        self.depth_cameras_compressed = [c.compressed for c in active_depth_cams]

        # Configuration attributes (populated from YAML)
        self.camera_topics = {}
        self.camera_info_topics = {}
        self.topic_to_cam = {}
        self.camera_shapes = {}
        self.depth_camera_topics = {}
        self.depth_camera_info_topics = {}
        self.depth_camera_shapes = {}
        self.joint_states_topic = ''
        self.cmd_vel_topic = ''
        self.odom_topic = ''
        self.has_mobile_base = False
        self.has_cmd_vel_y = False
        self.has_cmd_vel_z = False
        self.action_features = []
        self.all_subtasks_list = []
        self.subtask_label_to_idx = {}
        self.has_subtasks = False

        # Conversion tracking
        self.episode_stats = []
        self.skipped_bags = []  # [(bag_path, [missing_topics])]
        self.fps_warnings = []  # Episodes saved, but FPS was below the configured target.

        # One-shot timer to start conversion after the node is ready
        self.timer = self.create_timer(1.0, self.timer_callback)

    def timer_callback(self):
        """One-shot timer callback to trigger the conversion."""
        self.timer.cancel()
        try:
            self.convert()
        except Exception as e:
            self.get_logger().error(f'Conversion failed: {e}')
            import traceback
            self.get_logger().error(traceback.format_exc())
        finally:
            self.get_logger().info('Shutting down node...')
            raise SystemExit

    def _load_metadata(self):
        """Discover meta files, validate they agree, extract morphology from the first."""
        meta_files = self._discover_meta_files()
        if not meta_files:
            return None

        all_tasks, all_users = [], []
        ref = {'name': None, 'version': None, 'morphology': None, 'sensors': None}
        for idx, meta_file in enumerate(meta_files):
            with open(meta_file, 'r') as f:
                meta = yaml.safe_load(f)
            robot_info = meta.get('robot_info', {})
            morphology = robot_info.get('morphology', {})
            sensors_block = robot_info.get('sensors', {})

            if idx == 0:
                ref.update(
                    name=robot_info.get('name'), version=robot_info.get('version'),
                    morphology=morphology, sensors=sensors_block,
                )
                if not self._extract_morphology(morphology):
                    return None
            elif not self._validate_meta_matches(
                meta_file, robot_info, morphology, sensors_block, ref
            ):
                return None

            u_info = meta.get('user_info')
            if u_info and u_info not in all_users:
                all_users.append(u_info)
            for t_name, t_info in meta.get('recorded_bags', {}).get('tasks', {}).items():
                t_info['_meta_source_dir'] = os.path.dirname(meta_file)
                all_tasks.append((t_name, t_info))

        return all_tasks, all_users, robot_info, ref['sensors']

    def _discover_meta_files(self) -> list:
        if self.recorded_bags_meta_file:
            if not os.path.isfile(self.recorded_bags_meta_file):
                self.get_logger().error(
                    f'recorded_bags_meta_file not found: {self.recorded_bags_meta_file}'
                )
                return []
            return [self.recorded_bags_meta_file]
        meta_files = []
        for root, _, files in os.walk(self.rosbag_directory):
            for file in files:
                if file == 'recorded_bags_meta.yaml':
                    meta_files.append(os.path.join(root, file))
        if not meta_files:
            self.get_logger().error(
                f'No recorded_bags_meta.yaml found in {self.rosbag_directory}'
            )
            return []
        self.get_logger().info(f'Found {len(meta_files)} metadata file(s).')
        return meta_files

    def _extract_morphology(self, morphology: dict) -> bool:
        """Populate joint_states_topic/action_features/mobile-base fields; False aborts."""
        try:
            self.joint_states_topic = morphology.get('joint_states_topic', '/joint_states')
            self.action_features = []
            self.part_command_topics = set()
            self.has_mobile_base = False
            for part in morphology.get('parts', []):
                part_info = morphology.get(part, {})
                if not part_info.get('is_actionable', False):
                    continue
                if part in ['mobile_base', 'legs']:
                    self.has_mobile_base = True
                    self.has_cmd_vel_y = part_info.get('has_cmd_vel_y', False)
                    self.has_cmd_vel_z = part_info.get('has_cmd_vel_z', False)
                    self.cmd_vel_topic = part_info.get('cmd_vel_topic', '/cmd_vel')
                    self.odom_topic = part_info.get('odom_topic', '')
                    continue
                for j in part_info.get('joint_names', []):
                    if j in self.excluded_joints:
                        continue
                    if self.active_ros_names is not None and j not in self.active_ros_names:
                        continue
                    self.action_features.append(j)
                cmd_topic = part_info.get('command_topic', '')
                if cmd_topic:
                    self.part_command_topics.add(cmd_topic)
        except Exception as e:
            self.get_logger().error(f'Error extracting morphology features: {e}')
            return False
        if not self.action_features and not self.has_mobile_base:
            self.get_logger().error(
                'No actionable joints and no active mobile base found. Aborting.'
            )
            return False
        return True

    def _validate_meta_matches(
        self, meta_file, robot_info, morphology, sensors_block, ref
    ) -> bool:
        if robot_info.get('name') != ref['name'] or robot_info.get('version') != ref['version']:
            self.get_logger().error(
                f"Robot identity mismatch! Expected {ref['name']} v{ref['version']}, "
                f"got {robot_info.get('name')} v{robot_info.get('version')} in {meta_file}"
            )
            return False
        if not morphologies_match(ref['morphology'], morphology):
            self.get_logger().error(
                f'Morphology mismatch in {meta_file}. All sessions must share identical '
                'robot morphology (parts, is_actionable flags, joint_names). Aborting.'
            )
            return False
        if not sensors_match(ref['sensors'], sensors_block):
            self.get_logger().error(
                f'Sensor config mismatch in {meta_file}. All sessions '
                'must share identical sensor topics/shapes. Aborting.'
            )
            return False
        return True

    def _resolve_all_cameras(self, cam_maps, candidates) -> bool:
        all_cam_raw, all_cam_compressed, all_cam_info, all_cam_props = cam_maps
        all_cam_known = set(all_cam_raw.keys()) | set(all_cam_compressed.keys())
        selected_names = self.cameras_names if self.cameras_names else list(all_cam_known)

        from sobits_vla_common.image_codec import decode_depth_message, decode_image_message

        resolved = resolve_cameras(
            selected_names, list(self.cameras_compressed), all_cam_known,
            all_cam_raw, all_cam_compressed, all_cam_info, all_cam_props,
            candidates, decode_image_message, 'Camera', logger=self.get_logger(),
        )
        if resolved is None:
            return False
        self.camera_topics, self.camera_info_topics, self.camera_shapes = resolved
        self.topic_to_cam = {v: k for k, v in self.camera_topics.items()}

        if self.primary_camera not in self.camera_topics:
            fallback = list(self.camera_topics.keys())[0]
            self.get_logger().warning(
                f"Primary camera '{self.primary_camera}' not in selected cameras. "
                f"Falling back to '{fallback}'."
            )
            self.primary_camera = fallback

        if self.depth_cameras_names:
            depth_resolved = resolve_cameras(
                self.depth_cameras_names, list(self.depth_cameras_compressed), all_cam_known,
                all_cam_raw, all_cam_compressed, all_cam_info, all_cam_props,
                candidates, decode_depth_message, 'Depth camera', logger=self.get_logger(),
            )
            if depth_resolved is None:
                return False
            self.depth_camera_topics, self.depth_camera_info_topics, self.depth_camera_shapes = (
                depth_resolved
            )
            self.depth_topic_to_cam = {v: k for k, v in self.depth_camera_topics.items()}
        else:
            self.depth_camera_topics, self.depth_topic_to_cam = {}, {}
        return True

    def _build_features(self, all_tasks: list) -> dict:
        """Subtask index + action/state/camera feature schema for the LeRobot dataset."""
        all_subtasks_set = set()
        for _, task_info in all_tasks:
            for _, ep_meta in task_info.get('episodes', {}).items():
                subtasks = ep_meta.get('subtasks', {})
                if isinstance(subtasks, dict):
                    for _, st_info in subtasks.items():
                        if isinstance(st_info, dict) and 'label' in st_info:
                            all_subtasks_set.add(st_info['label'])
        self.all_subtasks_list = sorted(all_subtasks_set)
        if self.all_subtasks_list:
            self.all_subtasks_list.insert(0, 'No Subtask')
        self.subtask_label_to_idx = {
            label: i for i, label in enumerate(self.all_subtasks_list)
        }
        self.has_subtasks = len(self.all_subtasks_list) > 0

        self.base_keys = []
        if self.has_mobile_base:
            if self.has_cmd_vel_y and self.has_cmd_vel_z:
                self.base_keys = ['base_x', 'base_y', 'base_z', 'base_theta']
            elif self.has_cmd_vel_y:
                self.base_keys = ['base_x', 'base_y', 'base_theta']
            elif self.has_cmd_vel_z:
                self.base_keys = ['base_x', 'base_z', 'base_theta']
            else:
                self.base_keys = ['base_x', 'base_theta']

        joint_dim = len(self.action_features)
        base_dim = len(self.base_keys)
        total_dim = joint_dim + base_dim if self.has_mobile_base else joint_dim
        if self.has_mobile_base:
            action_names = self.action_features + self.base_keys
            state_names = self.action_features + self.base_keys
        else:
            action_names = self.action_features
            state_names = self.action_features

        features = {
            'action': {'dtype': 'float32', 'shape': (total_dim,), 'names': action_names},
            'observation.state': {
                'dtype': 'float32', 'shape': (total_dim,), 'names': state_names,
            },
        }
        if self.ee_pose_enabled:
            ee_names = ['x', 'y', 'z', 'roll', 'pitch', 'yaw']
            for ee_name, _, _ in self.ee_configs:
                key = f'observation.ee_pose.{ee_name}' if ee_name else 'observation.ee_pose'
                features[key] = {'dtype': 'float32', 'shape': (6,), 'names': ee_names}
                features[f'{key}.delta'] = {'dtype': 'float32', 'shape': (6,), 'names': ee_names}
        if self.has_subtasks:
            features['subtask_index'] = {
                'dtype': 'int64', 'shape': (1,), 'names': ['subtask_index'],
            }
        if not self.skip_cameras:
            for cam_name in self.camera_topics.keys():
                w, h = self.camera_shapes.get(cam_name, (640, 480))
                features[f'observation.images.{cam_name}'] = {
                    'dtype': 'video', 'shape': (3, h, w), 'names': ['channels', 'height', 'width'],
                }
        for cam_name in self.depth_camera_topics.keys():
            w, h = self.depth_camera_shapes.get(cam_name, (640, 480))
            features[f'observation.images.{cam_name}'] = {
                'dtype': 'video', 'shape': (h, w, 1), 'names': ['height', 'width', 'channels'],
                'info': {'is_depth_map': True},
            }
        return features

    def _make_writer(self, features: dict, robot_info: dict, all_users: list) -> DatasetWriter:
        return DatasetWriter(
            dataset_name=self.dataset_name, fps=self.fps, features=features,
            output_directory=self.output_directory,
            robot_type=robot_info.get('morphology', {}).get('type'),
            vcodec=self.vcodec, overwrite=self.overwrite, robot_info=robot_info,
            user_info=all_users, has_subtasks=self.has_subtasks,
            all_subtasks_list=self.all_subtasks_list, push_to_hub=self.push_to_hub,
            hub_private=self.hub_private, logger=self.get_logger(),
        )

    def _make_synthesizer(self) -> FrameSynthesizer:
        return FrameSynthesizer(
            fps=self.fps, sync_threshold=self.sync_threshold,
            downsample_tolerance=self.downsample_tolerance,
            use_relative_actions=self.use_relative_actions,
            skip_static_threshold=self.skip_static_threshold,
            action_features=self.action_features, has_mobile_base=self.has_mobile_base,
            base_keys=self.base_keys, ee_pose_enabled=self.ee_pose_enabled,
            ee_configs=self.ee_configs, skip_cameras=self.skip_cameras,
            primary_camera=self.primary_camera, camera_topics=self.camera_topics,
            depth_camera_topics=self.depth_camera_topics,
            subtask_label_to_idx=self.subtask_label_to_idx, logger=self.get_logger(),
        )

    def _run_episodes(self, dirs: list, all_tasks: list, pipeline: EpisodePipeline) -> None:
        """Convert every discovered episode, accumulating skipped_bags/fps_warnings/results."""
        self._episode_results = []
        found_names = {d.task_name for d in dirs}
        for task_name, task_info in all_tasks:
            if task_name not in found_names:
                meta_src = task_info.get('_meta_source_dir', self.rosbag_directory)
                fallback = os.path.join(meta_src, task_name)
                self.get_logger().warning(f'Directory not found: {fallback}')

        total_episodes = sum(len(d.episode_dirs) for d in dirs)
        current = 0
        for d in dirs:
            episodes_dict = d.task_info.get('episodes', {})
            instruction = d.task_info.get('label', d.task_info.get('instructions', d.task_name))
            for ep_path in d.episode_dirs:
                bag_files = [
                    f for f in os.listdir(ep_path)
                    if f.endswith('.db3') or f.endswith('.mcap')
                ]
                if not bag_files:
                    continue  # episode_discovery already filters this; defensive only
                bagfile = os.path.join(ep_path, bag_files[0])
                current += 1
                self.get_logger().info(f'[{current}/{total_episodes}] Processing: {bagfile}')

                ep = os.path.basename(ep_path)
                subtasks = episodes_dict.get(ep, {}).get('subtasks', {})
                result = pipeline.run(ep_path, bagfile, instruction, subtasks)
                if result is None:
                    continue
                if result.skipped:
                    entry = {'bag': result.bag, 'reason': result.skip_reason}
                    entry.update(result.skip_detail)
                    self.skipped_bags.append(entry)
                    continue
                if result.fps_warning:
                    self.fps_warnings.append(result.fps_warning)
                self._episode_results.append(result)

    def convert(self):
        self.get_logger().info('Starting dataset conversion...')
        self.get_logger().info(f'Target dataset name: {self.dataset_name}')
        self.get_logger().info(f'Reading from rosbags root: {self.rosbag_directory}')

        loaded = self._load_metadata()
        if loaded is None:
            return
        all_tasks, all_users, robot_info, ref_sensors = loaded

        cam_maps = _build_camera_maps(ref_sensors)
        if cam_maps is None:
            self.get_logger().error('No usable camera sensor type found in metadata. Exiting.')
            return

        dirs = discover_episodes(all_tasks, self.rosbag_directory)
        candidates = candidate_bag_dirs(all_tasks, self.rosbag_directory)
        if not self._resolve_all_cameras(cam_maps, candidates):
            return

        features = self._build_features(all_tasks)
        writer = self._make_writer(features, robot_info, all_users)
        synthesizer = self._make_synthesizer()
        pipeline = EpisodePipeline(
            self.camera_topics, self.depth_camera_topics, self.topic_to_cam,
            self.depth_topic_to_cam, self.joint_states_topic, self.part_command_topics,
            self.cmd_vel_topic, self.odom_topic, self.has_mobile_base, self.has_cmd_vel_y,
            self.has_cmd_vel_z, self.ee_pose_enabled, self.fps, synthesizer, writer,
            logger=self.get_logger(),
        )

        self._run_episodes(dirs, all_tasks, pipeline)

        conversion_params = {
            'rosbag_directory': self.rosbag_directory,
            'fps': self.fps,
            'vcodec': self.vcodec,
            'sync_threshold': self.sync_threshold,
            'downsample_tolerance': self.downsample_tolerance,
            'skip_static_threshold': self.skip_static_threshold,
            'use_relative_actions': self.use_relative_actions,
            'ee_pose_enabled': self.ee_pose_enabled,
            'cameras_skip': self.skip_cameras,
        }
        episode_dicts = [episode_stat_dict(r) for r in self._episode_results]
        writer.finalize(
            skipped_bags=self.skipped_bags,
            fps_warnings=self.fps_warnings,
            episode_stats=episode_dicts,
            conversion_params=conversion_params,
        )


def main(args=None):
    rclpy.init(args=args)
    node = RosbagConversionNode()
    try:
        rclpy.spin(node)
    except (KeyboardInterrupt, SystemExit):
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
