#!/usr/bin/env python3
"""
Multi-camera ros2bag to LeRobot dataset conversion.
Operates as a ROS 2 Node, loading config from the recorded_bags_meta.yaml
generated by the sobits_vla_rosbag_collection package.
"""
import os
import cv2
import yaml
import sys
import importlib
import io
import numpy as np
import torch
from pathlib import Path

import rclpy
from rclpy.node import Node

from sobits_vla_rosbag_conversion.tf_buffer import OfflineTFTree, mat_to_pose6d


def _ensure_runtime_dependencies() -> None:
    """Fail fast with a clear message when required Python packages are missing."""
    required_modules = [
        "rosbags",
        "lerobot",
        "pandas",
        "pyarrow",
    ]
    missing = []
    for module_name in required_modules:
        try:
            importlib.import_module(module_name)
        except Exception:
            missing.append(module_name)

    if missing:
        missing_str = ", ".join(missing)
        raise RuntimeError(
            "Missing required Python runtime dependencies: "
            f"{missing_str}. "
            f"Current interpreter: {sys.executable}. "
            "Install missing packages in this same environment."
        )


_ensure_runtime_dependencies()

from rosbags.highlevel import AnyReader
from lerobot.datasets.lerobot_dataset import LeRobotDataset


def _patch_uint8_quantile_stats() -> None:
    """Guard against lerobot 0.5.1's uint8 overflow in RunningQuantileStats.

    Images reach RunningQuantileStats.update() as raw uint8 [0, 255]
    (sample_images loads uint8 to save memory; the /255 happens AFTER stats).
    NumPy squaring of uint8 wraps mod 256 (255**2 -> 1), making
    mean_of_squares < mean**2, variance negative, and std clamped to 0.0 —
    which breaks image normalization downstream with NaN/inf.

    The fix also exists as a direct edit in our lerobot src checkout, but a
    pip (re)install of lerobot would silently revert it — this wrapper makes
    every conversion independent of which lerobot copy is installed. It is
    idempotent: if the underlying update() already casts, the extra cast here
    is a no-op.
    """
    try:
        from lerobot.datasets.compute_stats import RunningQuantileStats

        _orig_update = RunningQuantileStats.update

        def _patched_update(self, batch):
            if np.issubdtype(batch.dtype, np.integer):
                batch = batch.astype(np.float64)
            return _orig_update(self, batch)

        RunningQuantileStats.update = _patched_update
    except Exception:
        pass  # compute_stats layout changed — assume upstream fixed it


_patch_uint8_quantile_stats()

try:
    from PIL import Image as PILImage
except Exception:
    PILImage = None


class RosbagConversionNode(Node):
    def __init__(self):
        super().__init__('rosbag_conversion_node')

        # Suppress verbose SVT-AV1 encoder logs from PyAV/FFmpeg workers.
        os.environ.setdefault('SVT_LOG', '1')

        self.declare_parameter('rosbag_directory', '')
        self.declare_parameter('recorded_bags_meta_file', '')
        self.declare_parameter('dataset_name', 'MyDataset')
        self.declare_parameter('output_directory', '')
        self.declare_parameter('fps', 10)
        self.declare_parameter('vcodec', 'auto')
        self.declare_parameter('sync_threshold', 0.1)
        self.declare_parameter('downsample_tolerance', 0.015)
        self.declare_parameter('push_to_hub', False)
        self.declare_parameter('hub_private', False)
        self.declare_parameter('overwrite', False)
        self.declare_parameter('use_relative_actions', False)
        self.declare_parameter('skip_static_threshold', 0.0)
        self.declare_parameter('excluded_joints', [''])
        self.declare_parameter('ee_pose.enabled', False)
        self.declare_parameter('ee_pose.target_frame', 'base_link')
        self.declare_parameter('ee_pose.source_frame', 'hand_palm_link')
        self.declare_parameter('ee_pose.names', [''])
        self.declare_parameter('ee_pose.source_frames', [''])
        self.declare_parameter('ee_pose.target_frames', [''])
        self.declare_parameter('cameras.skip', False)
        self.declare_parameter('cameras.primary', 'head_camera')
        self.declare_parameter('cameras.names', [''])
        self.declare_parameter('cameras.compressed', [False])

        self.rosbag_directory = self.get_parameter('rosbag_directory').get_parameter_value().string_value
        self.recorded_bags_meta_file = self.get_parameter('recorded_bags_meta_file').get_parameter_value().string_value
        self.dataset_name = self.get_parameter('dataset_name').get_parameter_value().string_value
        output_dir = self.get_parameter('output_directory').get_parameter_value().string_value
        self.output_directory = Path(output_dir) if output_dir else None
        self.fps = self.get_parameter('fps').get_parameter_value().integer_value
        self.vcodec = self.get_parameter('vcodec').get_parameter_value().string_value
        self.sync_threshold = self.get_parameter('sync_threshold').get_parameter_value().double_value
        self.downsample_tolerance = self.get_parameter('downsample_tolerance').get_parameter_value().double_value
        self.push_to_hub = self.get_parameter('push_to_hub').get_parameter_value().bool_value
        self.hub_private = self.get_parameter('hub_private').get_parameter_value().bool_value
        self.overwrite = self.get_parameter('overwrite').get_parameter_value().bool_value
        self.use_relative_actions = self.get_parameter('use_relative_actions').get_parameter_value().bool_value
        self.skip_static_threshold = self.get_parameter('skip_static_threshold').get_parameter_value().double_value
        raw_excluded = self.get_parameter('excluded_joints').get_parameter_value().string_array_value
        self.excluded_joints = [j for j in raw_excluded if j]
        self.ee_pose_enabled = self.get_parameter('ee_pose.enabled').get_parameter_value().bool_value
        # Build ee_configs: list of (name, source_frame, target_frame)
        _ee_names   = [n for n in self.get_parameter('ee_pose.names').get_parameter_value().string_array_value if n]
        _ee_sources = [s for s in self.get_parameter('ee_pose.source_frames').get_parameter_value().string_array_value if s]
        _ee_targets = [t for t in self.get_parameter('ee_pose.target_frames').get_parameter_value().string_array_value if t]
        if _ee_names and _ee_sources:
            # Pad target_frames with the first entry if shorter than sources
            if not _ee_targets:
                _ee_targets = [self.get_parameter('ee_pose.target_frame').get_parameter_value().string_value] * len(_ee_names)
            while len(_ee_targets) < len(_ee_names):
                _ee_targets.append(_ee_targets[0])
            self.ee_configs = list(zip(_ee_names, _ee_sources, _ee_targets))
        else:
            # Legacy single-EE fallback
            _src = self.get_parameter('ee_pose.source_frame').get_parameter_value().string_value
            _tgt = self.get_parameter('ee_pose.target_frame').get_parameter_value().string_value
            self.ee_configs = [('', _src, _tgt)]  # name='' → feature key stays "observation.ee_pose"
        self.skip_cameras = self.get_parameter('cameras.skip').get_parameter_value().bool_value
        self.primary_camera = self.get_parameter('cameras.primary').get_parameter_value().string_value
        raw_names = self.get_parameter('cameras.names').get_parameter_value().string_array_value
        self.cameras_names = [n for n in raw_names if n]  # filter empty placeholder
        self.cameras_compressed = list(self.get_parameter('cameras.compressed').get_parameter_value().bool_array_value)

        # Configuration attributes (populated from YAML)
        self.camera_topics = {}
        self.camera_info_topics = {}
        self.topic_to_cam = {}
        self.camera_shapes = {}
        self.joint_states_topic = ""
        self.cmd_vel_topic = ""
        self.odom_topic = ""
        self.has_mobile_base = False
        self.has_cmd_vel_y = False
        self.has_cmd_vel_z = False
        self.action_features = []
        self.all_subtasks_list = []
        self.subtask_label_to_idx = {}
        self.has_subtasks = False

        # Conversion tracking
        self.episode_stats = []
        self.skipped_bags = []  # [(bag_path, [missing_topics])]
        self.fps_warnings = []  # Episodes saved, but FPS was below the configured target.

        # One-shot timer to start conversion after the node is ready
        self.timer = self.create_timer(1.0, self.timer_callback)

    def _decode_image_message(self, msg):
        """Decode ROS image/compressed-image message into RGB uint8 HWC array."""
        # CompressedImage-like messages usually expose a `format` field.
        if hasattr(msg, 'format'):
            data = msg.data
            if isinstance(data, memoryview):
                data = data.tobytes()
            if isinstance(data, (bytes, bytearray)):
                encoded = np.frombuffer(data, dtype=np.uint8)
            else:
                # rosbags can surface sequence payloads as Python lists/arrays.
                encoded = np.asarray(data, dtype=np.uint8)

            if encoded.size == 0:
                return None

            # Preferred path: OpenCV decode (fast). Some environments can fail due
            # OpenCV/Numpy ABI mismatch, so we fall back to Pillow decode.
            try:
                img = cv2.imdecode(np.ascontiguousarray(encoded), cv2.IMREAD_UNCHANGED)
            except Exception:
                img = None

            if img is not None:
                if img.ndim == 2:
                    return cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
                if img.shape[2] == 4:
                    return cv2.cvtColor(img, cv2.COLOR_BGRA2RGB)
                return cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

            if PILImage is None:
                return None
            try:
                pil_img = PILImage.open(io.BytesIO(encoded.tobytes())).convert('RGB')
                return np.asarray(pil_img, dtype=np.uint8)
            except Exception:
                return None

        # Raw Image message path — decode manually (rosbags.image removed in 0.10+)
        encoding = getattr(msg, 'encoding', '')
        data = msg.data
        if isinstance(data, memoryview):
            data = bytes(data)
        raw = np.frombuffer(data, dtype=np.uint8)
        h, w = msg.height, msg.width
        if encoding in ('mono8', '8UC1'):
            img = raw.reshape(h, w)
            return cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
        if encoding in ('mono16', '16UC1'):
            img = np.frombuffer(data, dtype=np.uint16).reshape(h, w)
            img8 = (img >> 8).astype(np.uint8)
            return cv2.cvtColor(img8, cv2.COLOR_GRAY2RGB)
        if encoding in ('rgb8',):
            return raw.reshape(h, w, 3).copy()
        if encoding in ('bgr8',):
            img = raw.reshape(h, w, 3)
            return cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        if encoding in ('rgba8',):
            img = raw.reshape(h, w, 4)
            return cv2.cvtColor(img, cv2.COLOR_RGBA2RGB)
        if encoding in ('bgra8',):
            img = raw.reshape(h, w, 4)
            return cv2.cvtColor(img, cv2.COLOR_BGRA2RGB)
        # Fallback: try to reshape as BGR and convert
        channels = len(raw) // (h * w) if h * w > 0 else 3
        img = raw.reshape(h, w, channels)
        if img.ndim == 2:
            return cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
        if img.shape[2] == 4:
            return cv2.cvtColor(img, cv2.COLOR_BGRA2RGB)
        return img

    def timer_callback(self):
        """One-shot timer callback to trigger the conversion."""
        self.timer.cancel()
        try:
            self.convert()
        except Exception as e:
            self.get_logger().error(f"Conversion failed: {e}")
            import traceback
            self.get_logger().error(traceback.format_exc())
        finally:
            self.get_logger().info("Shutting down node...")
            raise SystemExit

    def _persist_subtasks_metadata(self, dataset: LeRobotDataset) -> None:
        """Persist subtask mapping to meta/subtasks.parquet for LeRobot reload compatibility."""
        if not self.has_subtasks:
            return

        import pandas as pd

        subtasks_df = pd.DataFrame(
            {"subtask_index": np.arange(len(self.all_subtasks_list), dtype=np.int64)},
            index=pd.Index(self.all_subtasks_list, name="subtask"),
        )

        subtasks_path = Path(dataset.root) / "meta" / "subtasks.parquet"
        subtasks_path.parent.mkdir(parents=True, exist_ok=True)
        subtasks_df.to_parquet(subtasks_path)
        dataset.meta.subtasks = subtasks_df
        self.get_logger().info(f"Subtasks metadata saved to: {subtasks_path}")

    def _verify_subtasks_metadata(self, dataset_root: Path) -> None:
        """Reload dataset and verify that subtasks are persisted and loadable."""
        if not self.has_subtasks:
            return

        reloaded = LeRobotDataset(self.dataset_name, root=dataset_root)
        if reloaded.meta.subtasks is None:
            raise RuntimeError("Subtasks metadata was not persisted (meta.subtasks is None after reload).")
        if len(reloaded.meta.subtasks) != len(self.all_subtasks_list):
            raise RuntimeError(
                "Subtasks metadata size mismatch after reload: "
                f"expected {len(self.all_subtasks_list)}, got {len(reloaded.meta.subtasks)}"
            )
        if "subtask_index" not in reloaded.features:
            raise RuntimeError("Feature 'subtask_index' is missing after reload.")

    # Compare two morphology blocks for consistency
    def _morphologies_match(self, ref_morph: dict, other_morph: dict) -> bool:
        """Return True if the two morphology dicts are functionally equivalent."""
        for key in ["type", "has_mobile_base", "has_cmd_vel_y", "joint_states_topic"]:
            if ref_morph.get(key) != other_morph.get(key):
                return False
        ref_parts = ref_morph.get("parts", [])
        other_parts = other_morph.get("parts", [])
        if ref_parts != other_parts:
            return False
        for part in ref_parts:
            rp = ref_morph.get(part, {})
            op = other_morph.get(part, {})
            if rp.get("is_actionable") != op.get("is_actionable"):
                return False
            if rp.get("joint_names", []) != op.get("joint_names", []):
                return False
        return True

    def _interpolate_vector(self, series, target_time, dim):
        """Linearly interpolates a time-series list of (t, list_of_floats) at target_time."""
        if not series:
            return [0.0] * dim
        if len(series) == 1:
            return series[0][1]

        import bisect
        times = [s[0] for s in series]
        idx = bisect.bisect_right(times, target_time)

        if idx == 0:
            return series[0][1]
        if idx == len(series):
            return series[-1][1]

        t_prev, val_prev = series[idx - 1]
        t_next, val_next = series[idx]

        dt = t_next - t_prev
        if dt <= 0.0:
            return val_prev

        alpha = (target_time - t_prev) / dt
        return [(1.0 - alpha) * val_prev[j] + alpha * val_next[j] for j in range(dim)]

    def _interpolate_dict(self, series, target_time, keys):
        """Linearly interpolates a time-series list of (t, dict_of_floats) at target_time."""
        if not series:
            return {k: 0.0 for k in keys}
        if len(series) == 1:
            return {k: series[0][1].get(k, 0.0) for k in keys}

        import bisect
        times = [s[0] for s in series]
        idx = bisect.bisect_right(times, target_time)

        if idx == 0:
            return {k: series[0][1].get(k, 0.0) for k in keys}
        if idx == len(series):
            return {k: series[-1][1].get(k, 0.0) for k in keys}

        t_prev, dict_prev = series[idx - 1]
        t_next, dict_next = series[idx]

        dt = t_next - t_prev
        if dt <= 0.0:
            return {k: dict_prev.get(k, 0.0) for k in keys}

        alpha = (target_time - t_prev) / dt
        res = {}
        for k in keys:
            v_prev = dict_prev.get(k, 0.0)
            v_next = dict_next.get(k, 0.0)
            res[k] = (1.0 - alpha) * v_prev + alpha * v_next
        return res

    def _get_nearest_image(self, series, target_time):
        """Returns the nearest image (rawdata, msgtype, t) to target_time in the series."""
        if not series:
            return None, None, 0.0
        if len(series) == 1:
            return series[0][1], series[0][2], series[0][0]

        import bisect
        times = [s[0] for s in series]
        idx = bisect.bisect_right(times, target_time)

        if idx == 0:
            return series[0][1], series[0][2], series[0][0]
        if idx == len(series):
            return series[-1][1], series[-1][2], series[-1][0]

        t_prev, raw_prev, type_prev = series[idx - 1]
        t_next, raw_next, type_next = series[idx]

        if abs(target_time - t_prev) < abs(target_time - t_next):
            return raw_prev, type_prev, t_prev
        else:
            return raw_next, type_next, t_next

    def _any_arrived_in_interval(self, series, t_start, t_end):
        """Returns True if any message in the series arrived in the interval (t_start, t_end]."""
        if not series:
            return False
        import bisect
        times = [s[0] for s in series]
        idx = bisect.bisect_right(times, t_start)
        if idx < len(times) and times[idx] <= t_end:
            return True
        return False

    # Episode extraction
    def _extract_episode_data(self, bag_folder, subtasks_map, instruction):
        """
        Iterate over the bag and return a list of (timestamp, frame) tuples.
        Uses connection-level topic filter (O1) and cached topic_to_cam (O2).
        """
        # Buffers for time-series data
        joint_states_series = []          # list of (t, dict_pos, dict_vel)
        cmd_vel_series = []               # list of (t, list_vel)
        odom_series = []                  # list of (t, list_vel)
        cmd_joints_series = []            # list of (t, dict_pos)
        cam_series = {cam_name: [] for cam_name in self.camera_topics.keys()} # cam_name -> list of (t, rawdata, connection)

        tf_tree = OfflineTFTree() if self.ee_pose_enabled else None

        # Compute wanted topic set and filter connections
        wanted = set(self.camera_topics.values()) | {self.joint_states_topic}
        wanted |= self.part_command_topics  # JointTrajectory topics (required for action)
        if self.has_mobile_base and self.cmd_vel_topic:
            wanted.add(self.cmd_vel_topic)
        if self.has_mobile_base and self.odom_topic:
            wanted.add(self.odom_topic)
        if self.ee_pose_enabled:
            wanted |= {"/tf", "/tf_static"}

        with AnyReader([Path(bag_folder)]) as reader:
            # Pre-validate topics — log each missing topic with its purpose
            available = {c.topic for c in reader.connections}
            missing = wanted - available
            if missing:
                self.get_logger().error(f"Bag '{bag_folder}' is missing {len(missing)} required topic(s). Skipping episode.")
                for m in sorted(missing):
                    if m == self.joint_states_topic:
                        reason = "joint state observation"
                    elif m in self.part_command_topics:
                        reason = "joint command (action)"
                    elif m == self.cmd_vel_topic:
                        reason = "base velocity command (action.base)"
                    elif m in self.topic_to_cam:
                        reason = f"camera image ({self.topic_to_cam[m]})"
                    elif m in ("/tf", "/tf_static"):
                        reason = "TF transforms (ee_pose)"
                    else:
                        reason = "unknown"
                    self.get_logger().error(f"  missing: {m}  ({reason})")
                self.skipped_bags.append({
                    "bag": bag_folder,
                    "reason": "missing_topics",
                    "missing": {m: reason for m in sorted(missing) for reason in [
                        "joint_state" if m == self.joint_states_topic else
                        "joint_command" if m in self.part_command_topics else
                        "base_velocity" if m == self.cmd_vel_topic else
                        f"camera:{self.topic_to_cam[m]}" if m in self.topic_to_cam else
                        "tf" if m in ("/tf", "/tf_static") else "unknown"
                    ]},
                })
                return None

            # Filter at connection level
            connections = [c for c in reader.connections if c.topic in wanted]

            for connection, timestamp, rawdata in reader.messages(connections=connections):
                topic = connection.topic
                t_bag = timestamp * 1e-9

                if topic == self.joint_states_topic:
                    msg = reader.deserialize(rawdata, connection.msgtype)
                    t_sec = msg.header.stamp.sec + msg.header.stamp.nanosec * 1e-9
                    joint_pos = dict(zip(msg.name, msg.position))
                    velocity_values = getattr(msg, 'velocity', [])
                    joint_vel = dict(zip(msg.name, velocity_values)) if len(velocity_values) > 0 else {}
                    joint_states_series.append((t_sec, joint_pos, joint_vel))

                elif tf_tree is not None and topic in ("/tf", "/tf_static"):
                    msg = reader.deserialize(rawdata, connection.msgtype)
                    tf_tree.ingest(msg, is_static=(topic == "/tf_static"))

                elif topic in self.part_command_topics:
                    msg = reader.deserialize(rawdata, connection.msgtype)
                    if hasattr(msg, 'joint_names') and hasattr(msg, 'points') and len(msg.points) > 0:
                        target_point = msg.points[-1]
                        t_cmd = msg.header.stamp.sec + msg.header.stamp.nanosec * 1e-9 if hasattr(msg, 'header') and msg.header.stamp.sec > 0 else t_bag
                        commanded_joints = dict(zip(msg.joint_names, target_point.positions))
                        cmd_joints_series.append((t_cmd, commanded_joints))

                elif topic == self.cmd_vel_topic and self.has_mobile_base:
                    msg = reader.deserialize(rawdata, connection.msgtype)
                    t_sec = msg.header.stamp.sec + msg.header.stamp.nanosec * 1e-9 if hasattr(msg, 'header') else t_bag
                    if self.has_cmd_vel_y and self.has_cmd_vel_z:
                        cmd_vel = [msg.linear.x, msg.linear.y, msg.linear.z, msg.angular.z]
                    elif self.has_cmd_vel_y:
                        cmd_vel = [msg.linear.x, msg.linear.y, msg.angular.z]
                    elif self.has_cmd_vel_z:
                        cmd_vel = [msg.linear.x, msg.linear.z, msg.angular.z]
                    else:
                        cmd_vel = [msg.linear.x, msg.angular.z]
                    cmd_vel_series.append((t_sec, cmd_vel))

                elif topic == self.odom_topic and self.has_mobile_base:
                    msg = reader.deserialize(rawdata, connection.msgtype)
                    t_sec = msg.header.stamp.sec + msg.header.stamp.nanosec * 1e-9 if hasattr(msg, 'header') else t_bag
                    linear_x = msg.twist.twist.linear.x
                    linear_y = msg.twist.twist.linear.y
                    linear_z = msg.twist.twist.linear.z
                    angular_z = msg.twist.twist.angular.z
                    if self.has_cmd_vel_y and self.has_cmd_vel_z:
                        odom_vel = [linear_x, linear_y, linear_z, angular_z]
                    elif self.has_cmd_vel_y:
                        odom_vel = [linear_x, linear_y, angular_z]
                    elif self.has_cmd_vel_z:
                        odom_vel = [linear_x, linear_z, angular_z]
                    else:
                        odom_vel = [linear_x, angular_z]
                    odom_series.append((t_sec, odom_vel))

                elif topic in self.topic_to_cam:
                    cam_name = self.topic_to_cam[topic]
                    msg = reader.deserialize(rawdata, connection.msgtype)
                    t_sec = msg.header.stamp.sec + msg.header.stamp.nanosec * 1e-9
                    cam_series[cam_name].append((t_sec, rawdata, connection))

        if not cam_series[self.primary_camera]:
            self.get_logger().error(f"Bag '{bag_folder}' contains no primary camera images.")
            return None
        if not joint_states_series:
            self.get_logger().error(f"Bag '{bag_folder}' contains no joint states.")
            return None

        # Sort all buffers by timestamp to ensure binary search works
        joint_states_series.sort(key=lambda x: x[0])
        cmd_vel_series.sort(key=lambda x: x[0])
        odom_series.sort(key=lambda x: x[0])
        cmd_joints_series.sort(key=lambda x: x[0])
        for cam_name in cam_series:
            cam_series[cam_name].sort(key=lambda x: x[0])

        # Separate pos and vel for joints to simplify interpolation dict helper
        joint_pos_series = [(s[0], s[1]) for s in joint_states_series]
        joint_vel_series = [(s[0], s[2]) for s in joint_states_series]

        frames = []
        skipped_static = 0
        skipped_tf = 0
        skipped_img_decode = 0
        skipped_downsample = 0
        sync_deltas = []

        last_frame_time = 0.0
        min_frame_interval = 1.0 / self.fps if self.fps > 0 else 0.0

        # EE pose tracking — one prev_pose entry per configured EE
        prev_ee_poses = {name: None for name, _, _ in self.ee_configs}

        for t_sec, primary_raw, primary_conn in cam_series[self.primary_camera]:
            # Downsample: enforce minimum interval between frames (with tolerance for jitter)
            if min_frame_interval > 0.0 and last_frame_time > 0.0:
                if (t_sec - last_frame_time) < (min_frame_interval - self.downsample_tolerance):
                    skipped_downsample += 1
                    continue

            # Fetch secondary camera images at nearest time
            images = {}
            image_times = {self.primary_camera: t_sec}
            decoding_failed = False

            # First decode primary camera
            try:
                msg_prim = reader.deserialize(primary_raw, primary_conn.msgtype)
                img_prim = self._decode_image_message(msg_prim)
                if img_prim is None:
                    decoding_failed = True
                else:
                    images[self.primary_camera] = img_prim
            except Exception:
                decoding_failed = True

            if decoding_failed:
                skipped_img_decode += 1
                continue

            for cam_name in self.camera_topics.keys():
                if cam_name == self.primary_camera:
                    continue
                raw_img, conn_img, t_img = self._get_nearest_image(cam_series[cam_name], t_sec)
                if raw_img is None:
                    decoding_failed = True
                    break
                try:
                    msg_img = reader.deserialize(raw_img, conn_img.msgtype)
                    img = self._decode_image_message(msg_img)
                    if img is None:
                        decoding_failed = True
                        break
                    images[cam_name] = img
                    image_times[cam_name] = t_img
                except Exception:
                    decoding_failed = True
                    break

            if decoding_failed:
                skipped_img_decode += 1
                continue

            # Check sync difference for other cameras
            img_times = list(image_times.values())
            max_camera_diff = max(img_times) - min(img_times)

            # Interpolate joint state
            joint_pos = self._interpolate_dict(joint_pos_series, t_sec, self.action_features)
            joint_vel = self._interpolate_dict(joint_vel_series, t_sec, self.action_features)

            # Check if we have active base
            if self.has_mobile_base:
                cmd_vel = self._interpolate_vector(cmd_vel_series, t_sec, len(self.base_keys))
                odom_vel = self._interpolate_vector(odom_series, t_sec, len(self.base_keys))
            else:
                cmd_vel = None
                odom_vel = None

            # Check sync differences (using nearest message timestamps for sync warning logs only)
            import bisect
            def get_closest_t(series, target):
                if not series:
                    return target
                times = [s[0] for s in series]
                idx = bisect.bisect_left(times, target)
                if idx == 0:
                    return times[0]
                if idx == len(times):
                    return times[-1]
                if abs(times[idx] - target) < abs(times[idx - 1] - target):
                    return times[idx]
                return times[idx - 1]

            closest_joint_t = get_closest_t(joint_states_series, t_sec)
            joint_diff = abs(t_sec - closest_joint_t)

            closest_cmd_vel_t = get_closest_t(cmd_vel_series, t_sec) if self.has_mobile_base else t_sec
            cmd_vel_diff = abs(t_sec - closest_cmd_vel_t) if self.has_mobile_base else 0.0

            closest_odom_t = get_closest_t(odom_series, t_sec) if self.has_mobile_base else t_sec
            odom_diff = abs(t_sec - closest_odom_t) if self.has_mobile_base else 0.0

            max_sync = max(max_camera_diff, joint_diff, cmd_vel_diff, odom_diff)
            if max_sync > self.sync_threshold:
                self.get_logger().warn(
                    f"Sync threshold exceeded at t={t_sec:.3f}s: cam_diff={max_camera_diff:.3f}s, "
                    f"joint_diff={joint_diff:.3f}s, cmd_vel_diff={cmd_vel_diff:.3f}s, "
                    f"odom_diff={odom_diff:.3f}s"
                )
            sync_deltas.append(max_sync)

            # Skip static frames: skip if no joint velocity exceeds threshold
            if self.skip_static_threshold > 0.0:
                joint_vel_vals = [joint_vel[f] for f in self.action_features]
                if not np.any(np.abs(joint_vel_vals) > self.skip_static_threshold):
                    skipped_static += 1
                    continue

            # State: measured joint positions
            state = [joint_pos[feat] for feat in self.action_features]

            # Action: commanded joint positions
            action = []
            action_freshness = []
            for i, feat in enumerate(self.action_features):
                # Filter to only contain commands for this specific joint
                cmd_series_for_feat = [(t, d) for t, d in cmd_joints_series if feat in d]
                if cmd_series_for_feat and t_sec >= cmd_series_for_feat[0][0]:
                    cmd_val = self._interpolate_dict(cmd_series_for_feat, t_sec, [feat])[feat]
                    action.append(cmd_val)
                else:
                    # Fall back to future measured state (t_sec + 1.0/fps) to ensure valid actions/deltas
                    t_next = t_sec + (1.0 / self.fps if self.fps > 0 else 0.1)
                    next_joint_pos = self._interpolate_dict(joint_pos_series, t_next, [feat])
                    action.append(next_joint_pos[feat])

            # Freshness masks: did any message arrive in (last_frame_time, t_sec]?
            t_start = last_frame_time if last_frame_time > 0.0 else t_sec - (1.0 / self.fps if self.fps > 0 else 0.1)

            # If use_relative_actions is True, subtract joint state from joint action to get the delta command
            if self.use_relative_actions:
                action = [act_val - st_val for act_val, st_val in zip(action, state)]

            joint_dim = len(self.action_features)
            state_fresh = self._any_arrived_in_interval(joint_states_series, t_start, t_sec)

            # Action freshness (joints)
            for feat in self.action_features:
                cmd_series_for_feat = [(t, d) for t, d in cmd_joints_series if feat in d]
                if cmd_series_for_feat:
                    feat_fresh = self._any_arrived_in_interval(cmd_series_for_feat, t_start, t_sec)
                else:
                    # If action falls back to state, its freshness matches state freshness
                    feat_fresh = state_fresh
                action_freshness.append(feat_fresh)

            if self.has_mobile_base:
                state = state + list(odom_vel)
                action = action + list(cmd_vel)
                odom_fresh = self._any_arrived_in_interval(odom_series, t_start, t_sec)
                state_freshness = [state_fresh] * joint_dim + [odom_fresh] * len(self.base_keys)
                cmd_vel_fresh = self._any_arrived_in_interval(cmd_vel_series, t_start, t_sec)
                action_freshness = action_freshness + [cmd_vel_fresh] * len(self.base_keys)
            else:
                state_freshness = [state_fresh] * joint_dim

            frame = {
                "task": instruction,
                "action": torch.tensor(action, dtype=torch.float32),
                "observation.state": torch.tensor(state, dtype=torch.float32),
                # NOTE: auxiliary keys (action.is_fresh, action.delta,
                # action.base, observation.state.is_fresh) are intentionally
                # NOT included.  LeRobot tags anything starting with "action"
                # as ACTION and includes it in the PI0.5 denoising loss.
                # Including booleans and redundant representations here caused
                # training failure.
            }

            # End-effector pose via TF chain (supports multiple EEs)
            if tf_tree is not None:
                stamp_ns = int(t_sec * 1e9)
                ee_failed = False
                for ee_name, ee_src, ee_tgt in self.ee_configs:
                    ee_mat = tf_tree.resolve(ee_tgt, ee_src, stamp_ns)
                    if ee_mat is None:
                        skipped_tf += 1
                        if skipped_tf <= 5:
                            self.get_logger().warn(
                                f"TF lookup failed: '{ee_src}' → '{ee_tgt}' "
                                f"at t={t_sec:.3f}s. Skipping frame."
                            )
                        ee_failed = True
                        break
                    ee_abs = mat_to_pose6d(ee_mat)
                    prev = prev_ee_poses[ee_name]
                    if prev is not None:
                        for ax in range(3, 6):
                            diff = ee_abs[ax] - prev[ax]
                            if diff > np.pi:
                                ee_abs[ax] -= 2 * np.pi
                            elif diff < -np.pi:
                                ee_abs[ax] += 2 * np.pi
                        ee_rel = ee_abs - prev
                    else:
                        ee_rel = np.zeros(6, dtype=np.float32)
                    key = f"observation.ee_pose.{ee_name}" if ee_name else "observation.ee_pose"
                    frame[key] = torch.from_numpy(ee_abs.copy())
                    frame[f"{key}.delta"] = torch.from_numpy(ee_rel)
                    prev_ee_poses[ee_name] = ee_abs.copy()
                if ee_failed:
                    continue

            if not self.skip_cameras:
                for c_name in self.camera_topics.keys():
                    img_arr = np.ascontiguousarray(images[c_name].transpose(2, 0, 1))
                    frame[f"observation.images.{c_name}"] = torch.from_numpy(img_arr)

            # Subtask annotation
            if self.all_subtasks_list and subtasks_map:
                current_subtask_idx = 0
                for _, st_info in (subtasks_map.items() if isinstance(subtasks_map, dict) else {}):
                    start_t = st_info.get("start_timestamp", -1.0) if isinstance(st_info, dict) else -1.0
                    end_t = st_info.get("end_timestamp", float('inf')) if isinstance(st_info, dict) else float('inf')
                    if end_t == 0.0:
                        end_t = float('inf')
                    if start_t <= t_sec <= end_t:
                        label = st_info.get("label", "") if isinstance(st_info, dict) else ""
                        current_subtask_idx = self.subtask_label_to_idx.get(label, 0)
                        break
                frame["subtask_index"] = torch.tensor([current_subtask_idx], dtype=torch.int64)

            frames.append((t_sec, frame))
            last_frame_time = t_sec

        if skipped_tf > 5:
            self.get_logger().warn(f"TF lookup failed {skipped_tf} times total (suppressed after 5).")
        if skipped_img_decode > 0:
            self.get_logger().warn(f"Image decode failed {skipped_img_decode} times.")

        return frames, sync_deltas, skipped_static, skipped_tf, skipped_img_decode, skipped_downsample

    # Main conversion
    def convert(self):
        self.get_logger().info("Starting dataset conversion...")
        self.get_logger().info(f"Target dataset name: {self.dataset_name}")
        self.get_logger().info(f"Reading from rosbags root: {self.rosbag_directory}")

        # Discover metadata files
        meta_files = []
        if self.recorded_bags_meta_file:
            if not os.path.isfile(self.recorded_bags_meta_file):
                self.get_logger().error(
                    f"recorded_bags_meta_file not found: {self.recorded_bags_meta_file}"
                )
                return
            meta_files = [self.recorded_bags_meta_file]
        else:
            for root, _, files in os.walk(self.rosbag_directory):
                for file in files:
                    if file == "recorded_bags_meta.yaml":
                        meta_files.append(os.path.join(root, file))

        if not meta_files:
            self.get_logger().error(f"No recorded_bags_meta.yaml found in {self.rosbag_directory}")
            return

        self.get_logger().info(f"Found {len(meta_files)} metadata file(s).")

        all_tasks = []
        all_users = []
        robot_ref_name = None
        robot_ref_version = None
        ref_morphology = None
        robot_info = {}

        for idx, meta_file in enumerate(meta_files):
            with open(meta_file, "r") as f:
                meta = yaml.safe_load(f)

            robot_info = meta.get("robot_info", {})
            r_name = robot_info.get("name")
            r_vers = robot_info.get("version")
            morphology = robot_info.get("morphology", {})

            if idx == 0:
                robot_ref_name = r_name
                robot_ref_version = r_vers
                ref_morphology = morphology

                try:
                    self.joint_states_topic = morphology.get("joint_states_topic", "/joint_states")
                    parts = morphology.get("parts", [])

                    self.action_features = []  # joint names (excludes mobile base)
                    self.part_command_topics = set()  # topics carrying joint commands
                    for part in parts:
                        part_info = morphology.get(part, {})
                        if part_info.get("is_actionable", False):
                            if part in ["mobile_base", "legs"]:
                                self.has_mobile_base = True
                                self.has_cmd_vel_y = part_info.get("has_cmd_vel_y", False)
                                self.has_cmd_vel_z = part_info.get("has_cmd_vel_z", False)
                                self.cmd_vel_topic = part_info.get("cmd_vel_topic", "/cmd_vel")
                                self.odom_topic = part_info.get("odom_topic", "")
                            else:
                                for j in part_info.get("joint_names", []):
                                    if j not in self.excluded_joints:
                                        self.action_features.append(j)
                                cmd_topic = part_info.get("command_topic", "")
                                if cmd_topic:
                                    self.part_command_topics.add(cmd_topic)

                    if not self.action_features and not self.has_mobile_base:
                        self.get_logger().error("No actionable joints and no active mobile base found. Aborting.")
                        return
                except Exception as e:
                    self.get_logger().error(f"Error extracting morphology features: {e}")
                    return
            else:
                # Morphology comparison
                if r_name != robot_ref_name or r_vers != robot_ref_version:
                    self.get_logger().error(
                        f"Robot identity mismatch! Expected {robot_ref_name} v{robot_ref_version}, "
                        f"got {r_name} v{r_vers} in {meta_file}"
                    )
                    return
                if not self._morphologies_match(ref_morphology, morphology):
                    self.get_logger().error(
                        f"Morphology mismatch in {meta_file}. All sessions must share identical "
                        "robot morphology (parts, is_actionable flags, joint_names). Aborting."
                    )
                    return

            u_info = meta.get("user_info")
            if u_info and u_info not in all_users:
                all_users.append(u_info)

            for t_name, t_info in meta.get("recorded_bags", {}).get("tasks", {}).items():
                t_info["_meta_source_dir"] = os.path.dirname(meta_file)
                all_tasks.append((t_name, t_info))

        # Build flat per-camera maps from all sensor types
        sensors = robot_info.get("sensors", {})
        sensor_types = sensors.get("types", [])
        all_cam_raw = {}         # name -> raw topic
        all_cam_compressed = {}  # name -> compressed topic
        all_cam_info = {}        # name -> camera_info topic
        all_cam_props = {}       # name -> properties dict (width, height)

        for stype in sensor_types:
            sdata = sensors.get(stype, {})
            names = sdata.get("names", [])
            topics = sdata.get("topics", [])
            compressed_topics = sdata.get("compressed_topics", [])
            info_topics = sdata.get("info_topics", [])
            props = sdata.get("properties", {})
            for i, name in enumerate(names):
                if i < len(topics) and topics[i]:
                    all_cam_raw[name] = topics[i]
                if i < len(compressed_topics) and compressed_topics[i]:
                    all_cam_compressed[name] = compressed_topics[i]
                if i < len(info_topics) and info_topics[i]:
                    all_cam_info[name] = info_topics[i]
                all_cam_props[name] = props.get(name, {})

        if not all_cam_raw and not all_cam_compressed:
            self.get_logger().error("No usable camera sensor type found in metadata. Exiting.")
            return

        # Apply camera selection: use config list or fall back to all cameras
        all_cam_known = set(all_cam_raw.keys()) | set(all_cam_compressed.keys())
        selected_names = self.cameras_names if self.cameras_names else list(all_cam_known)
        selected_compressed = list(self.cameras_compressed)
        # Pad compressed flags with False if shorter than names
        if len(selected_compressed) < len(selected_names):
            selected_compressed += [False] * (len(selected_names) - len(selected_compressed))

        self.camera_topics = {}
        self.camera_info_topics = {}
        for name, use_compressed in zip(selected_names, selected_compressed):
            if name not in all_cam_known:
                self.get_logger().error(f"Camera '{name}' not found in metadata sensors. Aborting.")
                return
            if use_compressed:
                topic = all_cam_compressed.get(name, "")
                if not topic:
                    self.get_logger().warn(f"Camera '{name}': no compressed topic in metadata, falling back to raw.")
                    topic = all_cam_raw.get(name, "")
            else:
                topic = all_cam_raw.get(name, "")
            if not topic:
                self.get_logger().error(f"Camera '{name}': no topic available (raw or compressed). Aborting.")
                return
            self.camera_topics[name] = topic
            self.camera_info_topics[name] = all_cam_info.get(name, "")

        # O2: build cached reverse map once
        self.topic_to_cam = {v: k for k, v in self.camera_topics.items()}

        if self.primary_camera not in self.camera_topics:
            fallback = list(self.camera_topics.keys())[0]
            self.get_logger().warn(f"Primary camera '{self.primary_camera}' not in selected cameras. Falling back to '{fallback}'.")
            self.primary_camera = fallback

        # Resolve camera dimensions without modifying the decoded frames.
        self.camera_shapes = {}
        unresolved_cameras = []
        for cam_name in self.camera_topics.keys():
            props = all_cam_props.get(cam_name, {})
            width = props.get("width")
            height = props.get("height")
            if width and height:
                self.camera_shapes[cam_name] = (int(width), int(height))
            else:
                unresolved_cameras.append(cam_name)

        if unresolved_cameras:
            candidate_bag_dirs = []
            for _, task_info in all_tasks:
                meta_src = task_info.get("_meta_source_dir", self.rosbag_directory)
                bag_group = task_info.get("bag_path", task_info.get("bag_dir", ""))
                group_dir = os.path.join(meta_src, bag_group) if not bag_group.startswith("/") else bag_group
                if not os.path.isdir(group_dir):
                    continue
                for ep in sorted(os.listdir(group_dir)):
                    ep_path = os.path.join(group_dir, ep)
                    if not os.path.isdir(ep_path):
                        continue
                    if any(f.endswith(".db3") or f.endswith(".mcap") for f in os.listdir(ep_path)):
                        candidate_bag_dirs.append(ep_path)

            unresolved_set = set(unresolved_cameras)
            for bag_dir in candidate_bag_dirs:
                if not unresolved_set:
                    break
                try:
                    with AnyReader([Path(bag_dir)]) as reader:
                        info_topic_to_cam = {
                            self.camera_info_topics[name]: name
                            for name in unresolved_set
                            if self.camera_info_topics.get(name)
                        }
                        if not info_topic_to_cam:
                            break
                        connections = [c for c in reader.connections if c.topic in info_topic_to_cam]
                        for connection, _, rawdata in reader.messages(connections=connections):
                            cam_name = info_topic_to_cam.get(connection.topic)
                            if not cam_name or cam_name not in unresolved_set:
                                continue
                            msg = reader.deserialize(rawdata, connection.msgtype)
                            self.camera_shapes[cam_name] = (int(msg.width), int(msg.height))
                            unresolved_set.remove(cam_name)
                            if not unresolved_set:
                                break
                except Exception:
                    continue

            # If CameraInfo was unavailable, infer resolution from first image messages.
            for bag_dir in candidate_bag_dirs:
                if not unresolved_set:
                    break
                try:
                    with AnyReader([Path(bag_dir)]) as reader:
                        topic_to_cam = {
                            self.camera_topics[name]: name
                            for name in unresolved_set
                            if self.camera_topics.get(name)
                        }
                        if not topic_to_cam:
                            break
                        connections = [c for c in reader.connections if c.topic in topic_to_cam]
                        for connection, _, rawdata in reader.messages(connections=connections):
                            cam_name = topic_to_cam.get(connection.topic)
                            if not cam_name or cam_name not in unresolved_set:
                                continue
                            msg = reader.deserialize(rawdata, connection.msgtype)
                            try:
                                img = self._decode_image_message(msg)
                                if img is None:
                                    continue
                            except Exception:
                                continue
                            h, w = img.shape[:2]
                            self.camera_shapes[cam_name] = (int(w), int(h))
                            unresolved_set.remove(cam_name)
                            if not unresolved_set:
                                break
                except Exception:
                    continue

            if unresolved_set:
                unresolved_msgs = []
                for cam_name in sorted(unresolved_set):
                    info_topic = self.camera_info_topics.get(cam_name, "")
                    image_topic = self.camera_topics.get(cam_name, "")
                    unresolved_msgs.append(
                        f"camera='{cam_name}', info_topic='{info_topic}', image_topic='{image_topic}'"
                    )
                self.get_logger().error(
                    "Failed to resolve camera dimensions from metadata, camera_info, or image streams. "
                    "Please re-record metadata with sensor properties populated."
                )
                for msg in unresolved_msgs:
                    self.get_logger().error(f"  unresolved: {msg}")
                return

        # Subtask index
        all_subtasks_set = set()
        for _, task_info in all_tasks:
            for _, ep_meta in task_info.get("episodes", {}).items():
                subtasks = ep_meta.get("subtasks", {})
                if isinstance(subtasks, dict):
                    for _, st_info in subtasks.items():
                        if isinstance(st_info, dict) and "label" in st_info:
                            all_subtasks_set.add(st_info["label"])

        self.all_subtasks_list = sorted(list(all_subtasks_set))
        if self.all_subtasks_list:
            self.all_subtasks_list.insert(0, "No Subtask")
        self.subtask_label_to_idx = {label: i for i, label in enumerate(self.all_subtasks_list)}
        self.has_subtasks = len(self.all_subtasks_list) > 0

        # Feature schema
        self.base_keys = []
        if self.has_mobile_base:
            if self.has_cmd_vel_y and self.has_cmd_vel_z:
                self.base_keys = ["base_x", "base_y", "base_z", "base_theta"]
            elif self.has_cmd_vel_y:
                self.base_keys = ["base_x", "base_y", "base_theta"]
            elif self.has_cmd_vel_z:
                self.base_keys = ["base_x", "base_z", "base_theta"]
            else:
                self.base_keys = ["base_x", "base_theta"]

        joint_dim = len(self.action_features)
        base_dim = len(self.base_keys)
        total_dim = joint_dim + base_dim if self.has_mobile_base else joint_dim
        action_names = self.action_features + self.base_keys if self.has_mobile_base else self.action_features
        state_names = self.action_features + self.base_keys if self.has_mobile_base else self.action_features

        features = {
            # Joint action: commanded positions (absolute)
            # NOTE: Only "action" and "observation.state" are registered as dataset
            # features.  Auxiliary keys (action.is_fresh, action.delta, action.base,
            # observation.state.is_fresh) are still computed per-frame for debugging
            # but are NOT registered here.  LeRobot auto-discovers output features
            # from this dict and tags anything starting with "action" as ACTION type,
            # which PI0.5 includes in the flow-matching denoising loss.  Including
            # boolean freshness masks and redundant delta/base representations
            # dilutes learning and causes deployment failure.
            "action": {"dtype": "float32", "shape": (total_dim,), "names": action_names},
            # Joint state: measured positions from /joint_states
            "observation.state": {"dtype": "float32", "shape": (total_dim,), "names": state_names},
        }
        if self.ee_pose_enabled:
            ee_names = ["x", "y", "z", "roll", "pitch", "yaw"]
            for ee_name, _, _ in self.ee_configs:
                key = f"observation.ee_pose.{ee_name}" if ee_name else "observation.ee_pose"
                features[key] = {"dtype": "float32", "shape": (6,), "names": ee_names}
                features[f"{key}.delta"] = {"dtype": "float32", "shape": (6,), "names": ee_names}

        if self.has_subtasks:
            features["subtask_index"] = {"dtype": "int64", "shape": (1,), "names": ["subtask_index"]}

        if not self.skip_cameras:
            for cam_name in self.camera_topics.keys():
                w, h = self.camera_shapes.get(cam_name, (640, 480))
                features[f"observation.images.{cam_name}"] = {
                    "dtype": "video",
                    "shape": (3, h, w),
                    "names": ["channels", "height", "width"],  # shape is (C,H,W); image_writer expects CHW input and handles HWC→CHW transpose internally
                }

        # Resolve output root (mirrors LeRobot default logic) so we can check existence
        import shutil
        from lerobot.utils.constants import HF_LEROBOT_HOME
        dataset_root = self.output_directory if self.output_directory else HF_LEROBOT_HOME / self.dataset_name
        if self.overwrite and dataset_root.exists():
            self.get_logger().warn(f"overwrite=true: deleting existing dataset at {dataset_root}")
            shutil.rmtree(dataset_root)

        # Create dataset
        dataset = LeRobotDataset.create(
            repo_id=self.dataset_name,
            fps=self.fps,
            features=features,
            root=self.output_directory,
            robot_type=robot_info.get("morphology", {}).get("type"),
            video_backend="auto",
            vcodec=self.vcodec,
            streaming_encoding=True,
        )

        dataset.meta.info["robot_info"] = robot_info
        if all_users:
            dataset.meta.info["user_info"] = all_users if len(all_users) > 1 else all_users[0]

        # Count total episodes for progress logging
        total_episodes = 0
        for _, task_info in all_tasks:
            meta_src = task_info.get("_meta_source_dir", self.rosbag_directory)
            bag_group = task_info.get("bag_path", task_info.get("bag_dir", ""))
            group_dir = os.path.join(meta_src, bag_group) if not bag_group.startswith("/") else bag_group
            if os.path.isdir(group_dir):
                total_episodes += sum(
                    1 for ep in os.listdir(group_dir)
                    if os.path.isdir(os.path.join(group_dir, ep))
                    and any(f.endswith(".db3") or f.endswith(".mcap")
                            for f in os.listdir(os.path.join(group_dir, ep)))
                )

        current_episode_num = 0

        # Conversion loop
        for _, (task_name, task_info) in enumerate(all_tasks):
            meta_src = task_info.get("_meta_source_dir", self.rosbag_directory)
            bag_group = task_info.get("bag_path", task_info.get("bag_dir", task_name))
            group_dir = os.path.join(meta_src, bag_group) if not bag_group.startswith("/") else bag_group

            if not os.path.isdir(group_dir):
                group_dir = os.path.join(meta_src, task_name)
                if not os.path.isdir(group_dir):
                    self.get_logger().warn(f"Directory not found: {group_dir}")
                    continue

            episodes_dict = task_info.get("episodes", {})
            instruction = task_info.get("label", task_info.get("instructions", task_name))

            for ep in sorted(os.listdir(group_dir)):
                ep_path = os.path.join(group_dir, ep)
                if not os.path.isdir(ep_path):
                    continue
                bag_files = [f for f in os.listdir(ep_path) if f.endswith(".db3") or f.endswith(".mcap")]
                if not bag_files:
                    continue

                bagfile = os.path.join(ep_path, bag_files[0])
                current_episode_num += 1

                # progress bar
                self.get_logger().info(f"[{current_episode_num}/{total_episodes}] Processing: {bagfile}")

                ep_meta = episodes_dict.get(ep, {})
                subtasks = ep_meta.get("subtasks", {})

                try:
                    result = self._extract_episode_data(
                        os.path.dirname(bagfile),
                        subtasks_map=subtasks,
                        instruction=instruction,
                    )
                except Exception as e:
                    self.get_logger().error(f"Failed to read bag {bagfile}: {e}")
                    self.skipped_bags.append({
                        "bag": os.path.dirname(bagfile),
                        "reason": "read_error",
                        "error": str(e),
                    })
                    continue

                if result is None:
                    # Missing required topics — already logged and tracked in skipped_bags
                    continue
                frames, sync_deltas, ep_skipped_static, ep_skipped_tf, ep_skipped_img, ep_skipped_ds = result

                if not frames:
                    self.get_logger().warn(
                        f"No frames extracted from {bagfile} "
                        f"(downsample={ep_skipped_ds}, static={ep_skipped_static}, "
                        f"tf={ep_skipped_tf}, img_decode={ep_skipped_img})"
                    )
                    self.skipped_bags.append({
                        "bag": os.path.dirname(bagfile),
                        "reason": "no_frames",
                        "skipped_downsample": ep_skipped_ds,
                        "skipped_static": ep_skipped_static,
                        "skipped_tf": ep_skipped_tf,
                        "skipped_img_decode": ep_skipped_img,
                    })
                    continue

                # FPS validation — drop episodes that can't meet the configured rate
                if len(frames) > 1:
                    duration = frames[-1][0] - frames[0][0]
                    actual_fps = len(frames) / duration if duration > 0 else 0.0
                    if actual_fps < self.fps * 0.8:
                        self.get_logger().warn(
                            f"Proceeding with {bagfile}: actual fps ({actual_fps:.1f}) is below "
                            f"configured fps ({self.fps}) threshold (80%)."
                        )
                        self.fps_warnings.append({
                            "bag": os.path.dirname(bagfile),
                            "reason": "fps_below_target",
                            "actual_fps": round(actual_fps, 1),
                            "required_fps": self.fps,
                        })

                for _, frame in frames:
                    dataset.add_frame(frame)

                dataset.save_episode()

                # Accumulate episode stats
                ep_stat = {
                    "bag": os.path.basename(ep_path),
                    "task": instruction,
                    "frames": len(frames),
                    "skipped_downsample": ep_skipped_ds,
                    "skipped_static": ep_skipped_static,
                    "skipped_tf": ep_skipped_tf,
                    "skipped_img_decode": ep_skipped_img,
                }
                if sync_deltas:
                    ep_stat["sync_avg_ms"] = round(float(np.mean(sync_deltas) * 1000), 2)
                    ep_stat["sync_max_ms"] = round(float(np.max(sync_deltas) * 1000), 2)
                    ep_stat["sync_min_ms"] = round(float(np.min(sync_deltas) * 1000), 2)
                self.episode_stats.append(ep_stat)
                self.get_logger().info(f"  → Saved {len(frames)} frames.")

        if not self.episode_stats:
            self.get_logger().error("No episodes were successfully converted. Dataset is empty.")
        else:
            dataset.finalize()
            self._persist_subtasks_metadata(dataset)
            self._verify_subtasks_metadata(Path(dataset.root))
            self.get_logger().info(f"Dataset saved to: {dataset.root}")
            self.get_logger().info("Dataset creation completed!")

        if self.push_to_hub and self.episode_stats:
            self.get_logger().info(f"Pushing dataset to HuggingFace Hub as '{self.dataset_name}'...")
            dataset.push_to_hub(private=self.hub_private)
            self.get_logger().info("Push to Hub completed!")

        # Write conversion stats to YAML alongside the dataset
        stats_report = {
            "dataset_name": self.dataset_name,
            "rosbag_directory": self.rosbag_directory,
            "fps": self.fps,
            "vcodec": self.vcodec,
            "sync_threshold": self.sync_threshold,
            "downsample_tolerance": self.downsample_tolerance,
            "skip_static_threshold": self.skip_static_threshold,
            "use_relative_actions": self.use_relative_actions,
            "ee_pose_enabled": self.ee_pose_enabled,
            "cameras_skip": self.skip_cameras,
            "total_episodes": len(self.episode_stats),
            "total_frames": sum(s["frames"] for s in self.episode_stats),
            "skipped_bags": self.skipped_bags if self.skipped_bags else [],
            "fps_warnings": self.fps_warnings if self.fps_warnings else [],
            "episodes": self.episode_stats,
        }
        stats_path = Path(dataset.root) / "conversion_stats.yaml"
        with open(stats_path, "w") as f:
            yaml.dump(stats_report, f, default_flow_style=False, sort_keys=False)
        self.get_logger().info(f"Conversion stats saved to: {stats_path}")

        # Log summary
        self.get_logger().info(
            f"Summary: {len(self.episode_stats)} episodes, "
            f"{stats_report['total_frames']} frames, "
            f"{len(self.skipped_bags)} skipped bags, "
            f"{len(self.fps_warnings)} fps warnings"
        )


def main(args=None):
    rclpy.init(args=args)
    node = RosbagConversionNode()
    try:
        rclpy.spin(node)
    except (KeyboardInterrupt, SystemExit):
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
