#!/usr/bin/env python3

# Copyright (c) 2026, Team SOBITS
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the copyright holder nor the names of its
#   contributors may be used to endorse or promote products derived from this
#   software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

"""
Multi-camera ros2bag to LeRobot dataset conversion.

Operates as a ROS 2 Node, loading config from the recorded_bags_meta.yaml
generated by the sobits_vla_rosbag_collection package.
"""

import os
from pathlib import Path

import numpy as np
import rclpy
from rclpy.node import Node
from rosbags.highlevel import AnyReader
from sobits_vla_common import runtime_deps
from sobits_vla_common.lerobot_compat import apply_conversion_patches
from sobits_vla_rosbag_conversion.bag_reader import BagReader
from sobits_vla_rosbag_conversion.dataset_writer import DatasetWriter
from sobits_vla_rosbag_conversion.frame_synthesizer import FrameSynthesizer
import yaml


runtime_deps.ensure({
    'rosbags': 'pip install rosbags',
    'lerobot': 'pip install lerobot[training]~=0.6.0',
    'pandas': 'pip install pandas',
    'pyarrow': 'pip install pyarrow',
})

apply_conversion_patches()


def _default_output_root() -> Path:
    """
    Resolve the default dataset output root: <package_src>/lerobotdataset/.

    Works from the colcon install space (regular-copy installs) by walking up
    to the workspace root and locating the package under src/, and from
    source/symlink-install runs by finding the package root directly. Falls
    back to the installed share directory if the source tree can't be found.
    """
    candidate = Path(os.path.realpath(__file__)).parent
    for _ in range(8):
        # Running from the source tree (or --symlink-install): the package
        # root has both package.xml and the lerobotdataset/ folder.
        if (candidate / 'package.xml').exists() and (candidate / 'lerobotdataset').is_dir():
            return candidate / 'lerobotdataset'
        # Running from the install space: walk up to the workspace root and
        # look for the package under src/ (e.g. src/sobits_vla_tools/<pkg>).
        src_root = candidate / 'src'
        if src_root.is_dir():
            for pattern in ('*/sobits_vla_rosbag_conversion', '*/*/sobits_vla_rosbag_conversion'):
                for pkg_dir in src_root.glob(pattern):
                    if (pkg_dir / 'lerobotdataset').is_dir():
                        return pkg_dir / 'lerobotdataset'
        candidate = candidate.parent

    from ament_index_python.packages import get_package_share_directory
    return Path(get_package_share_directory('sobits_vla_rosbag_conversion')) / 'lerobotdataset'


class RosbagConversionNode(Node):
    def __init__(self):
        super().__init__('rosbag_conversion_node')

        from sobits_vla_common.lerobot_adapter import describe
        seam = describe()
        self.get_logger().info(
            f'lerobot seam: version={seam["version"]} is_v06={seam["is_v06"]} '
            f'unresolvable={seam["unresolvable"]}'
        )

        # Suppress verbose SVT-AV1 encoder logs from PyAV/FFmpeg workers.
        os.environ.setdefault('SVT_LOG', '1')

        self.declare_parameter('rosbag_directory', '')
        self.declare_parameter('recorded_bags_meta_file', '')
        self.declare_parameter('dataset_name', 'MyDataset')
        self.declare_parameter('output_directory', '')
        self.declare_parameter('fps', 10)
        self.declare_parameter('vcodec', 'auto')
        self.declare_parameter('sync_threshold', 0.1)
        self.declare_parameter('downsample_tolerance', 0.015)
        self.declare_parameter('push_to_hub', False)
        self.declare_parameter('hub_private', False)
        self.declare_parameter('overwrite', False)
        self.declare_parameter('use_relative_actions', False)
        self.declare_parameter('skip_static_threshold', 0.0)
        self.declare_parameter('excluded_joints', [''])
        self.declare_parameter('ee_pose.enabled', False)
        self.declare_parameter('ee_pose.target_frame', 'base_link')
        self.declare_parameter('ee_pose.source_frame', 'hand_palm_link')
        self.declare_parameter('ee_pose.names', [''])
        self.declare_parameter('ee_pose.source_frames', [''])
        self.declare_parameter('ee_pose.target_frames', [''])
        self.declare_parameter('cameras.skip', False)
        self.declare_parameter('cameras.primary', 'head_camera')
        self.declare_parameter('cameras.names', [''])
        self.declare_parameter('cameras.compressed', [False])

        self.rosbag_directory = (
            self.get_parameter('rosbag_directory').get_parameter_value().string_value
        )
        self.recorded_bags_meta_file = (
            self.get_parameter('recorded_bags_meta_file').get_parameter_value().string_value
        )
        self.dataset_name = (
            self.get_parameter('dataset_name').get_parameter_value().string_value
        )
        output_dir = (
            self.get_parameter('output_directory').get_parameter_value().string_value
        )
        if output_dir:
            self.output_directory = Path(output_dir)
        else:
            # Default documented in the conversion configs:
            # <package_src>/lerobotdataset/<dataset_name>
            self.output_directory = (
                _default_output_root() / self.dataset_name
            )
            self.get_logger().info(
                f'output_directory not set — defaulting to {self.output_directory}'
            )
        self.fps = self.get_parameter('fps').get_parameter_value().integer_value
        self.vcodec = self.get_parameter('vcodec').get_parameter_value().string_value
        self.sync_threshold = (
            self.get_parameter('sync_threshold').get_parameter_value().double_value
        )
        self.downsample_tolerance = (
            self.get_parameter('downsample_tolerance').get_parameter_value().double_value
        )
        self.push_to_hub = (
            self.get_parameter('push_to_hub').get_parameter_value().bool_value
        )
        self.hub_private = (
            self.get_parameter('hub_private').get_parameter_value().bool_value
        )
        self.overwrite = (
            self.get_parameter('overwrite').get_parameter_value().bool_value
        )
        self.use_relative_actions = (
            self.get_parameter('use_relative_actions').get_parameter_value().bool_value
        )
        self.skip_static_threshold = (
            self.get_parameter('skip_static_threshold').get_parameter_value().double_value
        )
        self.declare_parameter('robot_descriptor_id', '')
        self.robot_descriptor_id = (
            self.get_parameter('robot_descriptor_id').get_parameter_value().string_value
        )

        if self.robot_descriptor_id:
            from sobits_vla_common.robot_descriptor import load_robot_descriptor
            desc = load_robot_descriptor(self.robot_descriptor_id)

            # Excluded joints
            self.excluded_joints = desc.all_excluded_ros_names

            # EE config
            if desc.ee_poses:
                self.ee_pose_enabled = True
                self.ee_configs = [
                    (ee.name, ee.source_frame, ee.target_frame)
                    for ee in desc.ee_poses
                ]
            else:
                self.ee_pose_enabled = False
                self.ee_configs = []

            # Cameras
            self.skip_cameras = False
            active_cams = desc.active_cameras
            if active_cams:
                self.cameras_names = [c.name for c in active_cams]
                self.cameras_compressed = [c.compressed for c in active_cams]
                primary_param = (
                    self.get_parameter('cameras.primary').get_parameter_value().string_value
                )
                if primary_param == 'head_camera':
                    self.primary_camera = active_cams[0].name
                else:
                    self.primary_camera = primary_param
            else:
                self.cameras_names = []
                self.cameras_compressed = []
                self.skip_cameras = True
        else:
            # Fallback to legacy parameters
            raw_excluded = (
                self.get_parameter('excluded_joints').get_parameter_value().string_array_value
            )
            self.excluded_joints = [j for j in raw_excluded if j]
            self.ee_pose_enabled = (
                self.get_parameter('ee_pose.enabled').get_parameter_value().bool_value
            )
            _ee_names = [
                n for n in self.get_parameter('ee_pose.names')
                .get_parameter_value().string_array_value if n
            ]
            _ee_sources = [
                s for s in self.get_parameter('ee_pose.source_frames')
                .get_parameter_value().string_array_value if s
            ]
            _ee_targets = [
                t for t in self.get_parameter('ee_pose.target_frames')
                .get_parameter_value().string_array_value if t
            ]
            if _ee_names and _ee_sources:
                if not _ee_targets:
                    _ee_targets = [
                        self.get_parameter('ee_pose.target_frame')
                        .get_parameter_value().string_value
                    ] * len(_ee_names)
                while len(_ee_targets) < len(_ee_names):
                    _ee_targets.append(_ee_targets[0])
                self.ee_configs = list(zip(_ee_names, _ee_sources, _ee_targets))
            else:
                _src = (
                    self.get_parameter('ee_pose.source_frame')
                    .get_parameter_value().string_value
                )
                _tgt = (
                    self.get_parameter('ee_pose.target_frame')
                    .get_parameter_value().string_value
                )
                self.ee_configs = [('', _src, _tgt)]
            self.skip_cameras = (
                self.get_parameter('cameras.skip').get_parameter_value().bool_value
            )
            self.primary_camera = (
                self.get_parameter('cameras.primary').get_parameter_value().string_value
            )
            raw_names = (
                self.get_parameter('cameras.names').get_parameter_value().string_array_value
            )
            self.cameras_names = [n for n in raw_names if n]
            self.cameras_compressed = list(
                self.get_parameter('cameras.compressed')
                .get_parameter_value().bool_array_value
            )

        # Configuration attributes (populated from YAML)
        self.camera_topics = {}
        self.camera_info_topics = {}
        self.topic_to_cam = {}
        self.camera_shapes = {}
        self.joint_states_topic = ''
        self.cmd_vel_topic = ''
        self.odom_topic = ''
        self.has_mobile_base = False
        self.has_cmd_vel_y = False
        self.has_cmd_vel_z = False
        self.action_features = []
        self.all_subtasks_list = []
        self.subtask_label_to_idx = {}
        self.has_subtasks = False

        # Conversion tracking
        self.episode_stats = []
        self.skipped_bags = []  # [(bag_path, [missing_topics])]
        self.fps_warnings = []  # Episodes saved, but FPS was below the configured target.

        # One-shot timer to start conversion after the node is ready
        self.timer = self.create_timer(1.0, self.timer_callback)

    def timer_callback(self):
        """One-shot timer callback to trigger the conversion."""
        self.timer.cancel()
        try:
            self.convert()
        except Exception as e:
            self.get_logger().error(f'Conversion failed: {e}')
            import traceback
            self.get_logger().error(traceback.format_exc())
        finally:
            self.get_logger().info('Shutting down node...')
            raise SystemExit

    def _morphologies_match(self, ref_morph: dict, other_morph: dict) -> bool:
        """Return True if the two morphology dicts are functionally equivalent."""
        for key in ['type', 'has_mobile_base', 'has_cmd_vel_y', 'joint_states_topic']:
            if ref_morph.get(key) != other_morph.get(key):
                return False
        ref_parts = ref_morph.get('parts', [])
        other_parts = other_morph.get('parts', [])
        if ref_parts != other_parts:
            return False
        for part in ref_parts:
            rp = ref_morph.get(part, {})
            op = other_morph.get(part, {})
            if rp.get('is_actionable') != op.get('is_actionable'):
                return False
            if rp.get('joint_names', []) != op.get('joint_names', []):
                return False
        return True

    def convert(self):
        self.get_logger().info('Starting dataset conversion...')
        self.get_logger().info(f'Target dataset name: {self.dataset_name}')
        self.get_logger().info(f'Reading from rosbags root: {self.rosbag_directory}')

        # Discover metadata files
        meta_files = []
        if self.recorded_bags_meta_file:
            if not os.path.isfile(self.recorded_bags_meta_file):
                self.get_logger().error(
                    f'recorded_bags_meta_file not found: {self.recorded_bags_meta_file}'
                )
                return
            meta_files = [self.recorded_bags_meta_file]
        else:
            for root, _, files in os.walk(self.rosbag_directory):
                for file in files:
                    if file == 'recorded_bags_meta.yaml':
                        meta_files.append(os.path.join(root, file))

        if not meta_files:
            self.get_logger().error(
                f'No recorded_bags_meta.yaml found in {self.rosbag_directory}'
            )
            return

        self.get_logger().info(f'Found {len(meta_files)} metadata file(s).')

        all_tasks = []
        all_users = []
        robot_ref_name = None
        robot_ref_version = None
        ref_morphology = None
        robot_info = {}

        for idx, meta_file in enumerate(meta_files):
            with open(meta_file, 'r') as f:
                meta = yaml.safe_load(f)

            robot_info = meta.get('robot_info', {})
            r_name = robot_info.get('name')
            r_vers = robot_info.get('version')
            morphology = robot_info.get('morphology', {})

            if idx == 0:
                robot_ref_name = r_name
                robot_ref_version = r_vers
                ref_morphology = morphology

                try:
                    self.joint_states_topic = morphology.get('joint_states_topic', '/joint_states')
                    parts = morphology.get('parts', [])

                    self.action_features = []  # joint names (excludes mobile base)
                    self.part_command_topics = set()  # topics carrying joint commands
                    for part in parts:
                        part_info = morphology.get(part, {})
                        if part_info.get('is_actionable', False):
                            if part in ['mobile_base', 'legs']:
                                self.has_mobile_base = True
                                self.has_cmd_vel_y = part_info.get('has_cmd_vel_y', False)
                                self.has_cmd_vel_z = part_info.get('has_cmd_vel_z', False)
                                self.cmd_vel_topic = part_info.get('cmd_vel_topic', '/cmd_vel')
                                self.odom_topic = part_info.get('odom_topic', '')
                            else:
                                for j in part_info.get('joint_names', []):
                                    if j not in self.excluded_joints:
                                        self.action_features.append(j)
                                cmd_topic = part_info.get('command_topic', '')
                                if cmd_topic:
                                    self.part_command_topics.add(cmd_topic)

                    if not self.action_features and not self.has_mobile_base:
                        self.get_logger().error(
                            'No actionable joints and no active mobile base found. '
                            'Aborting.'
                        )
                        return
                except Exception as e:
                    self.get_logger().error(f'Error extracting morphology features: {e}')
                    return
            else:
                # Morphology comparison
                if r_name != robot_ref_name or r_vers != robot_ref_version:
                    self.get_logger().error(
                        'Robot identity mismatch! Expected '
                        f'{robot_ref_name} v{robot_ref_version}, '
                        f'got {r_name} v{r_vers} in {meta_file}'
                    )
                    return
                if not self._morphologies_match(ref_morphology, morphology):
                    self.get_logger().error(
                        f'Morphology mismatch in {meta_file}. All sessions must share identical '
                        'robot morphology (parts, is_actionable flags, joint_names). Aborting.'
                    )
                    return

            u_info = meta.get('user_info')
            if u_info and u_info not in all_users:
                all_users.append(u_info)

            for t_name, t_info in meta.get('recorded_bags', {}).get('tasks', {}).items():
                t_info['_meta_source_dir'] = os.path.dirname(meta_file)
                all_tasks.append((t_name, t_info))

        # Build flat per-camera maps from all sensor types
        sensors = robot_info.get('sensors', {})
        sensor_types = sensors.get('types', [])
        all_cam_raw = {}         # name -> raw topic
        all_cam_compressed = {}  # name -> compressed topic
        all_cam_info = {}        # name -> camera_info topic
        all_cam_props = {}       # name -> properties dict (width, height)

        for stype in sensor_types:
            sdata = sensors.get(stype, {})
            names = sdata.get('names', [])
            topics = sdata.get('topics', [])
            compressed_topics = sdata.get('compressed_topics', [])
            info_topics = sdata.get('info_topics', [])
            props = sdata.get('properties', {})
            for i, name in enumerate(names):
                if i < len(topics) and topics[i]:
                    all_cam_raw[name] = topics[i]
                if i < len(compressed_topics) and compressed_topics[i]:
                    all_cam_compressed[name] = compressed_topics[i]
                if i < len(info_topics) and info_topics[i]:
                    all_cam_info[name] = info_topics[i]
                all_cam_props[name] = props.get(name, {})

        if not all_cam_raw and not all_cam_compressed:
            self.get_logger().error('No usable camera sensor type found in metadata. Exiting.')
            return

        # Apply camera selection: use config list or fall back to all cameras
        all_cam_known = set(all_cam_raw.keys()) | set(all_cam_compressed.keys())
        selected_names = self.cameras_names if self.cameras_names else list(all_cam_known)
        selected_compressed = list(self.cameras_compressed)
        # Pad compressed flags with False if shorter than names
        if len(selected_compressed) < len(selected_names):
            selected_compressed += [False] * (len(selected_names) - len(selected_compressed))

        self.camera_topics = {}
        self.camera_info_topics = {}
        for name, use_compressed in zip(selected_names, selected_compressed):
            if name not in all_cam_known:
                self.get_logger().error(
                    f"Camera '{name}' not found in metadata sensors. Aborting."
                )
                return
            if use_compressed:
                topic = all_cam_compressed.get(name, '')
                if not topic:
                    self.get_logger().warn(
                        f"Camera '{name}': no compressed topic in metadata, "
                        'falling back to raw.'
                    )
                    topic = all_cam_raw.get(name, '')
            else:
                topic = all_cam_raw.get(name, '')
            if not topic:
                self.get_logger().error(
                    f"Camera '{name}': no topic available (raw or compressed). Aborting."
                )
                return
            self.camera_topics[name] = topic
            self.camera_info_topics[name] = all_cam_info.get(name, '')

        self.topic_to_cam = {v: k for k, v in self.camera_topics.items()}

        if self.primary_camera not in self.camera_topics:
            fallback = list(self.camera_topics.keys())[0]
            self.get_logger().warn(
                f"Primary camera '{self.primary_camera}' not in selected cameras. "
                f"Falling back to '{fallback}'."
            )
            self.primary_camera = fallback

        # Resolve camera dimensions without modifying the decoded frames.
        self.camera_shapes = {}
        unresolved_cameras = []
        for cam_name in self.camera_topics.keys():
            props = all_cam_props.get(cam_name, {})
            width = props.get('width')
            height = props.get('height')
            if width and height:
                self.camera_shapes[cam_name] = (int(width), int(height))
            else:
                unresolved_cameras.append(cam_name)

        if unresolved_cameras:
            candidate_bag_dirs = []
            for _, task_info in all_tasks:
                meta_src = task_info.get('_meta_source_dir', self.rosbag_directory)
                bag_group = task_info.get('bag_path', task_info.get('bag_dir', ''))
                if bag_group.startswith('/'):
                    group_dir = bag_group
                else:
                    group_dir = os.path.join(meta_src, bag_group)
                if not os.path.isdir(group_dir):
                    continue
                for ep in sorted(os.listdir(group_dir)):
                    ep_path = os.path.join(group_dir, ep)
                    if not os.path.isdir(ep_path):
                        continue
                    if any(f.endswith('.db3') or f.endswith('.mcap') for f in os.listdir(ep_path)):
                        candidate_bag_dirs.append(ep_path)

            unresolved_set = set(unresolved_cameras)
            for bag_dir in candidate_bag_dirs:
                if not unresolved_set:
                    break
                try:
                    with AnyReader([Path(bag_dir)]) as reader:
                        info_topic_to_cam = {
                            self.camera_info_topics[name]: name
                            for name in unresolved_set
                            if self.camera_info_topics.get(name)
                        }
                        if not info_topic_to_cam:
                            break
                        connections = [
                            c for c in reader.connections
                            if c.topic in info_topic_to_cam
                        ]
                        for connection, _, rawdata in reader.messages(connections=connections):
                            cam_name = info_topic_to_cam.get(connection.topic)
                            if not cam_name or cam_name not in unresolved_set:
                                continue
                            msg = reader.deserialize(rawdata, connection.msgtype)
                            self.camera_shapes[cam_name] = (int(msg.width), int(msg.height))
                            unresolved_set.remove(cam_name)
                            if not unresolved_set:
                                break
                except Exception:
                    continue

            # If CameraInfo was unavailable, infer resolution from first image messages.
            for bag_dir in candidate_bag_dirs:
                if not unresolved_set:
                    break
                try:
                    with AnyReader([Path(bag_dir)]) as reader:
                        topic_to_cam = {
                            self.camera_topics[name]: name
                            for name in unresolved_set
                            if self.camera_topics.get(name)
                        }
                        if not topic_to_cam:
                            break
                        connections = [c for c in reader.connections if c.topic in topic_to_cam]
                        for connection, _, rawdata in reader.messages(connections=connections):
                            cam_name = topic_to_cam.get(connection.topic)
                            if not cam_name or cam_name not in unresolved_set:
                                continue
                            msg = reader.deserialize(rawdata, connection.msgtype)
                            try:
                                from sobits_vla_rosbag_conversion.frame_synthesizer import (
                                    decode_image_message,
                                )
                                img = decode_image_message(msg)
                                if img is None:
                                    continue
                            except Exception:
                                continue
                            h, w = img.shape[:2]
                            self.camera_shapes[cam_name] = (int(w), int(h))
                            unresolved_set.remove(cam_name)
                            if not unresolved_set:
                                break
                except Exception:
                    continue

            if unresolved_set:
                unresolved_msgs = []
                for cam_name in sorted(unresolved_set):
                    info_topic = self.camera_info_topics.get(cam_name, '')
                    image_topic = self.camera_topics.get(cam_name, '')
                    unresolved_msgs.append(
                        f"camera='{cam_name}', info_topic='{info_topic}', "
                        f"image_topic='{image_topic}'"
                    )
                self.get_logger().error(
                    'Failed to resolve camera dimensions from metadata, '
                    'camera_info, or image streams. '
                    'Please re-record metadata with sensor properties populated.'
                )
                for msg in unresolved_msgs:
                    self.get_logger().error(f'  unresolved: {msg}')
                return

        # Subtask index
        all_subtasks_set = set()
        for _, task_info in all_tasks:
            for _, ep_meta in task_info.get('episodes', {}).items():
                subtasks = ep_meta.get('subtasks', {})
                if isinstance(subtasks, dict):
                    for _, st_info in subtasks.items():
                        if isinstance(st_info, dict) and 'label' in st_info:
                            all_subtasks_set.add(st_info['label'])

        self.all_subtasks_list = sorted(all_subtasks_set)
        if self.all_subtasks_list:
            self.all_subtasks_list.insert(0, 'No Subtask')
        self.subtask_label_to_idx = {
            label: i for i, label in enumerate(self.all_subtasks_list)
        }
        self.has_subtasks = len(self.all_subtasks_list) > 0

        # Feature schema
        self.base_keys = []
        if self.has_mobile_base:
            if self.has_cmd_vel_y and self.has_cmd_vel_z:
                self.base_keys = ['base_x', 'base_y', 'base_z', 'base_theta']
            elif self.has_cmd_vel_y:
                self.base_keys = ['base_x', 'base_y', 'base_theta']
            elif self.has_cmd_vel_z:
                self.base_keys = ['base_x', 'base_z', 'base_theta']
            else:
                self.base_keys = ['base_x', 'base_theta']

        joint_dim = len(self.action_features)
        base_dim = len(self.base_keys)
        total_dim = joint_dim + base_dim if self.has_mobile_base else joint_dim
        if self.has_mobile_base:
            action_names = self.action_features + self.base_keys
            state_names = self.action_features + self.base_keys
        else:
            action_names = self.action_features
            state_names = self.action_features

        features = {
            'action': {
                'dtype': 'float32',
                'shape': (total_dim,),
                'names': action_names
            },
            'observation.state': {
                'dtype': 'float32',
                'shape': (total_dim,),
                'names': state_names
            },
        }
        if self.ee_pose_enabled:
            ee_names = ['x', 'y', 'z', 'roll', 'pitch', 'yaw']
            for ee_name, _, _ in self.ee_configs:
                key = f'observation.ee_pose.{ee_name}' if ee_name else 'observation.ee_pose'
                features[key] = {'dtype': 'float32', 'shape': (6,), 'names': ee_names}
                features[f'{key}.delta'] = {'dtype': 'float32', 'shape': (6,), 'names': ee_names}

        if self.has_subtasks:
            features['subtask_index'] = {
                'dtype': 'int64',
                'shape': (1,),
                'names': ['subtask_index']
            }

        if not self.skip_cameras:
            for cam_name in self.camera_topics.keys():
                w, h = self.camera_shapes.get(cam_name, (640, 480))
                features[f'observation.images.{cam_name}'] = {
                    'dtype': 'video',
                    'shape': (3, h, w),
                    'names': ['channels', 'height', 'width'],
                }

        # Initialize dataset writer
        writer = DatasetWriter(
            dataset_name=self.dataset_name,
            fps=self.fps,
            features=features,
            output_directory=self.output_directory,
            robot_type=robot_info.get('morphology', {}).get('type'),
            vcodec=self.vcodec,
            overwrite=self.overwrite,
            robot_info=robot_info,
            user_info=all_users,
            has_subtasks=self.has_subtasks,
            all_subtasks_list=self.all_subtasks_list,
            push_to_hub=self.push_to_hub,
            hub_private=self.hub_private,
            logger=self.get_logger(),
        )

        # Initialize frame synthesizer
        synthesizer = FrameSynthesizer(
            fps=self.fps,
            sync_threshold=self.sync_threshold,
            downsample_tolerance=self.downsample_tolerance,
            use_relative_actions=self.use_relative_actions,
            skip_static_threshold=self.skip_static_threshold,
            action_features=self.action_features,
            has_mobile_base=self.has_mobile_base,
            base_keys=self.base_keys,
            ee_pose_enabled=self.ee_pose_enabled,
            ee_configs=self.ee_configs,
            skip_cameras=self.skip_cameras,
            primary_camera=self.primary_camera,
            camera_topics=self.camera_topics,
            subtask_label_to_idx=self.subtask_label_to_idx,
            logger=self.get_logger(),
        )

        # Count total episodes for progress logging
        total_episodes = 0
        for _, task_info in all_tasks:
            meta_src = task_info.get('_meta_source_dir', self.rosbag_directory)
            bag_group = task_info.get('bag_path', task_info.get('bag_dir', ''))
            if bag_group.startswith('/'):
                group_dir = bag_group
            else:
                group_dir = os.path.join(meta_src, bag_group)
            if os.path.isdir(group_dir):
                total_episodes += sum(
                    1 for ep in os.listdir(group_dir)
                    if os.path.isdir(os.path.join(group_dir, ep))
                    and any(f.endswith('.db3') or f.endswith('.mcap')
                            for f in os.listdir(os.path.join(group_dir, ep)))
                )

        current_episode_num = 0

        # Conversion loop
        for _, (task_name, task_info) in enumerate(all_tasks):
            meta_src = task_info.get('_meta_source_dir', self.rosbag_directory)
            bag_group = task_info.get('bag_path', task_info.get('bag_dir', task_name))
            if bag_group.startswith('/'):
                group_dir = bag_group
            else:
                group_dir = os.path.join(meta_src, bag_group)

            if not os.path.isdir(group_dir):
                group_dir = os.path.join(meta_src, task_name)
                if not os.path.isdir(group_dir):
                    self.get_logger().warn(f'Directory not found: {group_dir}')
                    continue

            episodes_dict = task_info.get('episodes', {})
            instruction = task_info.get('label', task_info.get('instructions', task_name))

            for ep in sorted(os.listdir(group_dir)):
                ep_path = os.path.join(group_dir, ep)
                if not os.path.isdir(ep_path):
                    continue
                bag_files = [
                    f for f in os.listdir(ep_path)
                    if f.endswith('.db3') or f.endswith('.mcap')
                ]
                if not bag_files:
                    continue

                bagfile = os.path.join(ep_path, bag_files[0])
                current_episode_num += 1

                self.get_logger().info(
                    f'[{current_episode_num}/{total_episodes}] Processing: {bagfile}'
                )

                ep_meta = episodes_dict.get(ep, {})
                subtasks = ep_meta.get('subtasks', {})

                # Construct expected topic set for BagReader check
                wanted = set(self.camera_topics.values()) | {self.joint_states_topic}
                wanted |= self.part_command_topics
                if self.has_mobile_base and self.cmd_vel_topic:
                    wanted.add(self.cmd_vel_topic)
                if self.has_mobile_base and self.odom_topic:
                    wanted.add(self.odom_topic)
                if self.ee_pose_enabled:
                    wanted |= {'/tf', '/tf_static'}

                bag_reader = BagReader(os.path.dirname(bagfile), logger=self.get_logger())
                missing = bag_reader.check_missing_topics(wanted)
                if missing:
                    self.get_logger().error(
                        f"Bag '{os.path.dirname(bagfile)}' is missing "
                        f'{len(missing)} required topic(s). Skipping episode.'
                    )
                    missing_report = {}
                    for m in sorted(missing):
                        if m == self.joint_states_topic:
                            reason = 'joint state observation'
                        elif m in self.part_command_topics:
                            reason = 'joint command (action)'
                        elif m == self.cmd_vel_topic:
                            reason = 'base velocity command (action.base)'
                        elif m in self.topic_to_cam:
                            reason = f'camera image ({self.topic_to_cam[m]})'
                        elif m in ('/tf', '/tf_static'):
                            reason = 'TF transforms (ee_pose)'
                        else:
                            reason = 'unknown'
                        self.get_logger().error(f'  missing: {m}  ({reason})')
                        missing_report[m] = (
                            'joint_state' if m == self.joint_states_topic else
                            'joint_command' if m in self.part_command_topics else
                            'base_velocity' if m == self.cmd_vel_topic else
                            f'camera:{self.topic_to_cam[m]}' if m in self.topic_to_cam else
                            'tf' if m in ('/tf', '/tf_static') else 'unknown'
                        )
                    self.skipped_bags.append({
                        'bag': os.path.dirname(bagfile),
                        'reason': 'missing_topics',
                        'missing': missing_report,
                    })
                    continue

                try:
                    bag_series = bag_reader.read_topic_series(
                        wanted_topics=wanted,
                        topic_to_cam=self.topic_to_cam,
                        part_command_topics=self.part_command_topics,
                        cmd_vel_topic=self.cmd_vel_topic,
                        odom_topic=self.odom_topic,
                        joint_states_topic=self.joint_states_topic,
                        ee_pose_enabled=self.ee_pose_enabled,
                        has_mobile_base=self.has_mobile_base,
                        has_cmd_vel_y=self.has_cmd_vel_y,
                        has_cmd_vel_z=self.has_cmd_vel_z
                    )

                    result = synthesizer.synthesize(
                        bag_series=bag_series,
                        subtasks_map=subtasks,
                        instruction=instruction,
                    )
                except Exception as e:
                    self.get_logger().error(f'Failed to read/process bag {bagfile}: {e}')
                    import traceback
                    self.get_logger().error(traceback.format_exc())
                    self.skipped_bags.append({
                        'bag': os.path.dirname(bagfile),
                        'reason': 'read_error',
                        'error': str(e),
                    })
                    continue

                if result is None:
                    continue

                (
                    frames,
                    sync_deltas,
                    ep_skipped_static,
                    ep_skipped_tf,
                    ep_skipped_img,
                    ep_skipped_ds,
                ) = result

                if not frames:
                    self.get_logger().warn(
                        f'No frames extracted from {bagfile} '
                        f'(downsample={ep_skipped_ds}, static={ep_skipped_static}, '
                        f'tf={ep_skipped_tf}, img_decode={ep_skipped_img})'
                    )
                    self.skipped_bags.append({
                        'bag': os.path.dirname(bagfile),
                        'reason': 'no_frames',
                        'skipped_downsample': ep_skipped_ds,
                        'skipped_static': ep_skipped_static,
                        'skipped_tf': ep_skipped_tf,
                        'skipped_img_decode': ep_skipped_img,
                    })
                    continue

                # FPS validation
                if len(frames) > 1:
                    duration = frames[-1][0] - frames[0][0]
                    actual_fps = len(frames) / duration if duration > 0 else 0.0
                    if actual_fps < self.fps * 0.8:
                        self.get_logger().warn(
                            f'Proceeding with {bagfile}: actual fps ({actual_fps:.1f}) is below '
                            f'configured fps ({self.fps}) threshold (80%).'
                        )
                        self.fps_warnings.append({
                            'bag': os.path.dirname(bagfile),
                            'reason': 'fps_below_target',
                            'actual_fps': round(actual_fps, 1),
                            'required_fps': self.fps,
                        })

                for _, frame in frames:
                    writer.add_frame(frame)

                writer.save_episode()

                # Accumulate episode stats
                ep_stat = {
                    'bag': os.path.basename(ep_path),
                    'task': instruction,
                    'frames': len(frames),
                    'skipped_downsample': ep_skipped_ds,
                    'skipped_static': ep_skipped_static,
                    'skipped_tf': ep_skipped_tf,
                    'skipped_img_decode': ep_skipped_img,
                }
                if sync_deltas:
                    ep_stat['sync_avg_ms'] = round(float(np.mean(sync_deltas) * 1000), 2)
                    ep_stat['sync_max_ms'] = round(float(np.max(sync_deltas) * 1000), 2)
                    ep_stat['sync_min_ms'] = round(float(np.min(sync_deltas) * 1000), 2)
                self.episode_stats.append(ep_stat)
                self.get_logger().info(f'  → Saved {len(frames)} frames.')

        # Finalize dataset
        conversion_params = {
            'rosbag_directory': self.rosbag_directory,
            'fps': self.fps,
            'vcodec': self.vcodec,
            'sync_threshold': self.sync_threshold,
            'downsample_tolerance': self.downsample_tolerance,
            'skip_static_threshold': self.skip_static_threshold,
            'use_relative_actions': self.use_relative_actions,
            'ee_pose_enabled': self.ee_pose_enabled,
            'cameras_skip': self.skip_cameras,
        }
        writer.finalize(
            skipped_bags=self.skipped_bags,
            fps_warnings=self.fps_warnings,
            episode_stats=self.episode_stats,
            conversion_params=conversion_params,
        )


def main(args=None):
    rclpy.init(args=args)
    node = RosbagConversionNode()
    try:
        rclpy.spin(node)
    except (KeyboardInterrupt, SystemExit):
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
