#!/usr/bin/env python3
"""
Multi-camera ros2bag to LeRobot dataset conversion.
Operates as a ROS 2 Node, loading config from the recorded_bags_meta.yaml
generated by the sobits_vla_rosbag_collection package.
"""
import os
import cv2
import yaml
import numpy as np
import torch
from pathlib import Path

import rclpy
from rclpy.node import Node

from rosbags.highlevel import AnyReader
from rosbags.image import message_to_cvimage
from lerobot.datasets.lerobot_dataset import LeRobotDataset


class RosbagConversionNode(Node):
    def __init__(self):
        super().__init__('rosbag_conversion_node')

        self.declare_parameter('rosbag_directory', '')
        self.declare_parameter('dataset_name', 'MyDataset')
        self.declare_parameter('primary_camera', 'head_camera')
        self.declare_parameter('skip_cameras', False)

        self.rosbag_directory = self.get_parameter('rosbag_directory').get_parameter_value().string_value
        self.dataset_name = self.get_parameter('dataset_name').get_parameter_value().string_value
        self.primary_camera = self.get_parameter('primary_camera').get_parameter_value().string_value
        self.skip_cameras = self.get_parameter('skip_cameras').get_parameter_value().bool_value

        # Configuration attributes (populated from YAML)
        self.camera_topics = {}
        self.topic_to_cam = {}
        self.joint_states_topic = ""
        self.cmd_vel_topic = ""
        self.odom_topic = ""
        self.sync_threshold = 0.1
        self.has_mobile_base = False
        self.has_cmd_vel_y = False
        self.has_cmd_vel_z = False
        self.action_features = []
        self.all_subtasks_list = []
        self.subtask_label_to_idx = {}
        self.has_subtasks = False

        # Episode quality tracking
        self.episode_stats = []

        # One-shot timer to start conversion after the node is ready
        self.timer = self.create_timer(1.0, self.timer_callback)

    def timer_callback(self):
        """One-shot timer callback to trigger the conversion."""
        self.timer.cancel()
        try:
            self.convert()
        except Exception as e:
            self.get_logger().error(f"Conversion failed: {e}")
            import traceback
            self.get_logger().error(traceback.format_exc())
        finally:
            self.get_logger().info("Shutting down node...")
            raise SystemExit

    # ─────────────────────────────────────────────────────────────────────────
    # Helper: compare two morphology blocks for consistency
    # ─────────────────────────────────────────────────────────────────────────
    def _morphologies_match(self, ref_morph: dict, other_morph: dict) -> bool:
        """Return True if the two morphology dicts are functionally equivalent."""
        for key in ["type", "has_mobile_base", "has_cmd_vel_y", "joint_states_topic"]:
            if ref_morph.get(key) != other_morph.get(key):
                return False
        ref_parts = ref_morph.get("parts", [])
        other_parts = other_morph.get("parts", [])
        if ref_parts != other_parts:
            return False
        for part in ref_parts:
            rp = ref_morph.get(part, {})
            op = other_morph.get(part, {})
            if rp.get("is_actionable") != op.get("is_actionable"):
                return False
            if rp.get("joint_names", []) != op.get("joint_names", []):
                return False
        return True

    # ─────────────────────────────────────────────────────────────────────────
    # Episode extraction
    # ─────────────────────────────────────────────────────────────────────────
    def _extract_episode_data(self, bag_folder, subtasks_map):
        """
        Iterate over the bag and return a list of (timestamp, frame) tuples.
        Uses connection-level topic filter (O1) and cached topic_to_cam (O2).
        """
        frames = []
        images = {cam_name: None for cam_name in self.camera_topics.keys()}
        image_times = {cam_name: 0.0 for cam_name in self.camera_topics.keys()}
        latest_joint_state = None
        latest_joint_time = 0.0
        latest_cmd_vel = [0.0, 0.0, 0.0] if self.has_cmd_vel_y else ([0.0, 0.0] if self.has_mobile_base else None)
        latest_cmd_vel_time = 0.0

        # O1: compute wanted topic set and filter connections
        wanted = set(self.camera_topics.values()) | {self.joint_states_topic}
        if self.has_mobile_base and self.cmd_vel_topic:
            wanted.add(self.cmd_vel_topic)

        sync_deltas = []  # for F6 quality stats

        with AnyReader([Path(bag_folder)]) as reader:
            # F3: pre-validate topics
            available = {c.topic for c in reader.connections}
            missing = wanted - available
            if missing:
                self.get_logger().warn(f"Bag {bag_folder} missing topics: {missing}. Skipping.")
                return []

            # O1: filter at connection level
            connections = [c for c in reader.connections if c.topic in wanted]

            for connection, timestamp, rawdata in reader.messages(connections=connections):
                topic = connection.topic
                t_bag = timestamp * 1e-9

                # Bug #3 fix: strict if / elif / elif chain
                if topic == self.joint_states_topic:
                    msg = reader.deserialize(rawdata, connection.msgtype)
                    joint_pos = dict(zip(msg.name, msg.position))
                    t_sec = msg.header.stamp.sec + msg.header.stamp.nanosec * 1e-9
                    latest_joint_state = [joint_pos.get(feat, 0.0) for feat in self.action_features]
                    latest_joint_time = t_sec

                elif topic == self.cmd_vel_topic and self.has_mobile_base:
                    msg = reader.deserialize(rawdata, connection.msgtype)
                    t_sec = msg.header.stamp.sec + msg.header.stamp.nanosec * 1e-9 if hasattr(msg, 'header') else t_bag
                    if self.has_cmd_vel_y and self.has_cmd_vel_z:
                        latest_cmd_vel = [msg.linear.x, msg.linear.y, msg.linear.z, msg.angular.z]
                    elif self.has_cmd_vel_y:
                        latest_cmd_vel = [msg.linear.x, msg.linear.y, msg.angular.z]
                    elif self.has_cmd_vel_z:
                        latest_cmd_vel = [msg.linear.x, msg.linear.z, msg.angular.z]
                    else:
                        latest_cmd_vel = [msg.linear.x, msg.angular.z]
                    latest_cmd_vel_time = t_sec

                elif topic in self.topic_to_cam:
                    cam_name = self.topic_to_cam[topic]
                    msg = reader.deserialize(rawdata, connection.msgtype)
                    img = message_to_cvimage(msg)
                    if len(img.shape) == 3 and img.shape[2] == 3:
                        if msg.encoding in ['bgr8', 'bgra8']:
                            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
                    t_sec = msg.header.stamp.sec + msg.header.stamp.nanosec * 1e-9
                    images[cam_name] = img
                    image_times[cam_name] = t_sec

                    # Snapshot trigger: primary camera
                    if cam_name == self.primary_camera and latest_joint_state is not None:
                        # Bug #4 fix: require all cameras but only reset primary
                        if any(v is None for v in images.values()):
                            continue
                        if self.has_mobile_base and latest_cmd_vel is None:
                            continue

                        # Sync checks
                        img_times = list(image_times.values())
                        max_camera_diff = max(img_times) - min(img_times)
                        joint_diff = abs(image_times[self.primary_camera] - latest_joint_time)
                        cmd_vel_diff = abs(image_times[self.primary_camera] - latest_cmd_vel_time) if self.has_mobile_base else 0.0
                        max_sync = max(max_camera_diff, joint_diff, cmd_vel_diff)

                        if max_sync > self.sync_threshold:
                            self.get_logger().warn(
                                f"Sync threshold exceeded: cam_diff={max_camera_diff:.3f}s, "
                                f"joint_diff={joint_diff:.3f}s, cmd_vel_diff={cmd_vel_diff:.3f}s"
                            )
                        sync_deltas.append(max_sync)

                        action = latest_joint_state + (latest_cmd_vel if self.has_mobile_base else [])
                        frame = {
                            "action": torch.tensor(action, dtype=torch.float32),
                            "observation.state": torch.tensor(action, dtype=torch.float32),
                        }

                        if not self.skip_cameras:
                            for c_name in self.camera_topics.keys():
                                # O4: avoid redundant contiguous copy via numpy path
                                img_arr = np.ascontiguousarray(images[c_name].transpose(2, 0, 1))
                                frame[f"observation.images.{c_name}"] = torch.from_numpy(img_arr)

                        # Subtask annotation
                        if self.all_subtasks_list and subtasks_map:
                            current_subtask_idx = 0
                            for st_key, st_info in (subtasks_map.items() if isinstance(subtasks_map, dict) else {}):
                                start_t = st_info.get("start_timestamp", -1.0) if isinstance(st_info, dict) else -1.0
                                end_t = st_info.get("end_timestamp", float('inf')) if isinstance(st_info, dict) else float('inf')
                                if end_t == 0.0:
                                    end_t = float('inf')
                                if start_t <= t_sec <= end_t:
                                    label = st_info.get("label", "") if isinstance(st_info, dict) else ""
                                    # O3: O(1) lookup
                                    current_subtask_idx = self.subtask_label_to_idx.get(label, 0)
                                    break
                            frame["subtask_index"] = torch.tensor([current_subtask_idx], dtype=torch.int64)

                        frames.append((t_sec, frame))
                        # Bug #4 fix: only reset primary camera to trigger next snapshot
                        images[self.primary_camera] = None

        return frames, sync_deltas

    # ─────────────────────────────────────────────────────────────────────────
    # Main conversion
    # ─────────────────────────────────────────────────────────────────────────
    def convert(self):
        self.get_logger().info("Starting dataset conversion...")
        self.get_logger().info(f"Target dataset name: {self.dataset_name}")
        self.get_logger().info(f"Reading from rosbags root: {self.rosbag_directory}")

        # Discover metadata files
        meta_files = []
        for root, _, files in os.walk(self.rosbag_directory):
            for file in files:
                if file == "recorded_bags_meta.yaml":
                    meta_files.append(os.path.join(root, file))

        if not meta_files:
            self.get_logger().error(f"No recorded_bags_meta.yaml found in {self.rosbag_directory}")
            return

        self.get_logger().info(f"Found {len(meta_files)} metadata file(s).")

        all_tasks = []
        all_users = []
        robot_ref_name = None
        robot_ref_version = None
        ref_morphology = None
        robot_info = {}

        for idx, meta_file in enumerate(meta_files):
            with open(meta_file, "r") as f:
                meta = yaml.safe_load(f)

            robot_info = meta.get("robot_info", {})
            r_name = robot_info.get("name")
            r_vers = robot_info.get("version")
            morphology = robot_info.get("morphology", {})

            if idx == 0:
                robot_ref_name = r_name
                robot_ref_version = r_vers
                ref_morphology = morphology

                convert_info = meta.get("convert_info", {})
                fps = convert_info.get("fps", 10)
                self.sync_threshold = convert_info.get("sync_threshold", 0.1)

                try:
                    self.joint_states_topic = morphology.get("joint_states_topic", "/joint_states")
                    parts = morphology.get("parts", [])

                    self.action_features = []
                    for part in parts:
                        part_info = morphology.get(part, {})
                        if part_info.get("is_actionable", False):
                            self.action_features.extend(part_info.get("joint_names", []))
                            if part in ["mobile_base", "legs"]:
                                self.has_mobile_base = True
                                self.has_cmd_vel_y = part_info.get("has_cmd_vel_y", False)
                                self.has_cmd_vel_z = part_info.get("has_cmd_vel_z", False)
                                self.cmd_vel_topic = part_info.get("cmd_vel_topic", "/cmd_vel")
                                self.odom_topic = part_info.get("odom_topic", "")

                    if not self.action_features and not self.has_mobile_base:
                        self.get_logger().warn("No actionable joints and no active mobile base found.")
                except Exception as e:
                    self.get_logger().error(f"Error extracting morphology features: {e}")
                    return
            else:
                # Bug #6: full morphology comparison
                if r_name != robot_ref_name or r_vers != robot_ref_version:
                    self.get_logger().error(
                        f"Robot identity mismatch! Expected {robot_ref_name} v{robot_ref_version}, "
                        f"got {r_name} v{r_vers} in {meta_file}"
                    )
                    return
                if not self._morphologies_match(ref_morphology, morphology):
                    self.get_logger().error(
                        f"Morphology mismatch in {meta_file}. All sessions must share identical "
                        "robot morphology (parts, is_actionable flags, joint_names). Aborting."
                    )
                    return

            u_info = meta.get("user_info")
            if u_info and u_info not in all_users:
                all_users.append(u_info)

            # Bug #5: iterate tasks dict directly (no tasks_list)
            for t_name, t_info in meta.get("recorded_bags", {}).get("tasks", {}).items():
                t_info["_meta_source_dir"] = os.path.dirname(meta_file)
                all_tasks.append((t_name, t_info))

        # ── Camera sensor discovery ──────────────────────────────────────────
        sensors = robot_info.get("sensors", {})
        sensor_types = sensors.get("types", [])
        camera_data = None

        for stype in sensor_types:
            sdata = sensors.get(stype, {})
            names = sdata.get("names", [])
            topics = sdata.get("topics", [])
            if self.primary_camera in names and names and topics:
                camera_data = {"names": names, "topics": topics, "sdata": sdata}
                self.get_logger().info(f"Found primary camera '{self.primary_camera}' in sensor type '{stype}'")
                break

        if camera_data is None:
            for stype in sensor_types:
                sdata = sensors.get(stype, {})
                names = sdata.get("names", [])
                topics = sdata.get("topics", [])
                if names and topics:
                    camera_data = {"names": names, "topics": topics, "sdata": sdata}
                    self.get_logger().warn(
                        f"Primary camera '{self.primary_camera}' not found. Falling back to sensor type '{stype}'."
                    )
                    break

        if camera_data is None:
            self.get_logger().error("No usable camera sensor type found in yaml. Exiting.")
            return

        self.camera_topics = {n: t for n, t in zip(camera_data["names"], camera_data["topics"])}
        # O2: build cached reverse map once
        self.topic_to_cam = {v: k for k, v in self.camera_topics.items()}

        if self.primary_camera not in self.camera_topics:
            fallback = list(self.camera_topics.keys())[0]
            self.get_logger().warn(f"Primary camera '{self.primary_camera}' not in topics. Falling back to '{fallback}'.")
            self.primary_camera = fallback

        # ── Subtask index ──────────────────────────────────────────────────
        all_subtasks_set = set()
        for _, task_info in all_tasks:
            for _, ep_meta in task_info.get("episodes", {}).items():
                subtasks = ep_meta.get("subtasks", {})
                if isinstance(subtasks, dict):
                    for _, st_info in subtasks.items():
                        if isinstance(st_info, dict) and "label" in st_info:
                            all_subtasks_set.add(st_info["label"])

        self.all_subtasks_list = sorted(list(all_subtasks_set))
        if self.all_subtasks_list:
            self.all_subtasks_list.insert(0, "No Subtask")
        # O3: build the O(1) lookup dict
        self.subtask_label_to_idx = {label: i for i, label in enumerate(self.all_subtasks_list)}
        self.has_subtasks = len(self.all_subtasks_list) > 0

        # ── Feature schema ────────────────────────────────────────────────
        cmd_vel_keys = []
        if self.has_mobile_base:
            if self.has_cmd_vel_y and self.has_cmd_vel_z:
                cmd_vel_keys = ["cmd_vel_x", "cmd_vel_y", "cmd_vel_z", "cmd_vel_theta"]
            elif self.has_cmd_vel_y:
                cmd_vel_keys = ["cmd_vel_x", "cmd_vel_y", "cmd_vel_theta"]
            elif self.has_cmd_vel_z:
                cmd_vel_keys = ["cmd_vel_x", "cmd_vel_z", "cmd_vel_theta"]
            else:
                cmd_vel_keys = ["cmd_vel_x", "cmd_vel_theta"]

        action_dim = len(self.action_features) + len(cmd_vel_keys)
        features = {
            "action": {"dtype": "float32", "shape": (action_dim,), "names": self.action_features + cmd_vel_keys},
            "observation.state": {"dtype": "float32", "shape": (action_dim,), "names": self.action_features + cmd_vel_keys},
        }
        if self.has_subtasks:
            features["subtask_index"] = {"dtype": "int64", "shape": (1,), "names": ["subtask_index"]}

        if not self.skip_cameras:
            sdata = camera_data["sdata"]
            for cam_name in camera_data["names"]:
                props = sdata.get("properties", {}).get(cam_name, {})
                w = props.get("width", 640)
                h = props.get("height", 480)
                features[f"observation.images.{cam_name}"] = {
                    "dtype": "video",
                    "shape": (3, h, w),
                    "names": ["channels", "height", "width"],
                }

        # ── Create dataset ────────────────────────────────────────────────
        dataset = LeRobotDataset.create(
            repo_id=self.dataset_name,
            fps=fps,
            features=features,
            video_backend="auto",
            streaming_encoding=True,
        )

        if self.has_subtasks:
            import pandas as pd
            dataset.meta.subtasks = pd.DataFrame({"subtask": self.all_subtasks_list})

        if hasattr(dataset, "info"):
            dataset.info["robot_info"] = robot_info
            if all_users:
                dataset.info["user_info"] = all_users if len(all_users) > 1 else all_users[0]

        # ── Count total episodes for progress logging (F2) ───────────────
        total_episodes = 0
        for _, task_info in all_tasks:
            meta_src = task_info.get("_meta_source_dir", self.rosbag_directory)
            bag_group = task_info.get("bag_path", task_info.get("bag_dir", ""))
            group_dir = os.path.join(meta_src, bag_group) if not bag_group.startswith("/") else bag_group
            if os.path.isdir(group_dir):
                total_episodes += sum(
                    1 for ep in os.listdir(group_dir)
                    if os.path.isdir(os.path.join(group_dir, ep))
                    and any(f.endswith(".db3") or f.endswith(".mcap")
                            for f in os.listdir(os.path.join(group_dir, ep)))
                )

        first_episode_done = False
        current_episode_num = 0

        # ── Conversion loop ───────────────────────────────────────────────
        for _, (task_name, task_info) in enumerate(all_tasks):
            meta_src = task_info.get("_meta_source_dir", self.rosbag_directory)
            bag_group = task_info.get("bag_path", task_info.get("bag_dir", task_name))
            group_dir = os.path.join(meta_src, bag_group) if not bag_group.startswith("/") else bag_group

            if not os.path.isdir(group_dir):
                group_dir = os.path.join(meta_src, task_name)
                if not os.path.isdir(group_dir):
                    self.get_logger().warn(f"Directory not found: {group_dir}")
                    continue

            episodes_dict = task_info.get("episodes", {})
            instruction = task_info.get("label", task_info.get("instructions", task_name))

            for ep in sorted(os.listdir(group_dir)):
                ep_path = os.path.join(group_dir, ep)
                if not os.path.isdir(ep_path):
                    continue
                bag_files = [f for f in os.listdir(ep_path) if f.endswith(".db3") or f.endswith(".mcap")]
                if not bag_files:
                    continue

                bagfile = os.path.join(ep_path, bag_files[0])
                current_episode_num += 1

                # F2: progress bar
                self.get_logger().info(f"[{current_episode_num}/{total_episodes}] Processing: {bagfile}")

                ep_meta = episodes_dict.get(ep, {})
                subtasks = ep_meta.get("subtasks", {})

                result = self._extract_episode_data(os.path.dirname(bagfile), subtasks_map=subtasks)
                if not result:
                    self.get_logger().warn(f"No frames extracted from {bagfile}")
                    continue
                frames, sync_deltas = result

                if not frames:
                    self.get_logger().warn(f"No frames extracted from {bagfile}")
                    continue

                # F5: FPS validation on first episode
                if not first_episode_done and len(frames) > 1:
                    first_episode_done = True
                    duration = frames[-1][0] - frames[0][0]
                    if duration > 0:
                        actual_fps = len(frames) / duration
                        if actual_fps < fps * 0.8:
                            self.get_logger().warn(
                                f"Actual frame rate ({actual_fps:.1f} fps) is significantly lower than "
                                f"configured dataset fps ({fps}). Consider reducing fps in record_settings."
                            )

                for _, frame in frames:
                    dataset.add_frame(frame)

                dataset.save_episode(task=instruction)

                # F6: accumulate episode stats
                if sync_deltas:
                    self.episode_stats.append({
                        "bag": os.path.basename(ep_path),
                        "frames": len(frames),
                        "avg_sync_ms": np.mean(sync_deltas) * 1000,
                        "max_sync_ms": np.max(sync_deltas) * 1000,
                        "min_sync_ms": np.min(sync_deltas) * 1000,
                    })
                self.get_logger().info(f"  → Saved {len(frames)} frames.")

        dataset.finalize()
        self.get_logger().info("Dataset creation completed!")

        # F6: episode quality report
        if self.episode_stats:
            self.get_logger().info("\n── Episode Quality Report ──────────────────────────────────────────")
            self.get_logger().info(f"{'Episode':<30} {'Frames':>7} {'Avg(ms)':>9} {'Max(ms)':>9} {'Min(ms)':>9}")
            self.get_logger().info("─" * 70)
            for s in self.episode_stats:
                self.get_logger().info(
                    f"{s['bag']:<30} {s['frames']:>7} {s['avg_sync_ms']:>9.1f} "
                    f"{s['max_sync_ms']:>9.1f} {s['min_sync_ms']:>9.1f}"
                )
            self.get_logger().info("─" * 70)


def main(args=None):
    rclpy.init(args=args)
    node = RosbagConversionNode()
    try:
        rclpy.spin(node)
    except (KeyboardInterrupt, SystemExit):
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
