/**:
  ros__parameters:
    # Control settings for the gamepad
    gamepad_config:
      # Gamepad type (e.g., "dualshock4", "keyboard", "quest")
      name: "quest"
      button_cooldown_duration: 0.5 # Cooldown duration for buttons (seconds)
      # Mapping of gamepad buttons to actions
      dualshock4:
        button_mapping:
          record: 7 # Top
          pause: 7 # Top
          save: 6 # Left
          delete: 6 # Right
      quest:
        button_mapping:
          record: 4 # Right controller (A button)
          pause: 4 # Right controller (A button)
          save: 5 # Right controller (B button)
          delete: 5 # Right controller (B button)
      keyboard:
        button_mapping:
          record: "r"
          save: "s"
          delete: "d"
