/**:
  ros__parameters:
    # Robot information
    robot_info:
      # Name of the robot
      name: "sobit_light"
      # Version of the robot
      version: "1.0.0"
      # Description of the robot
      morphology:
        # Type of the robot (e.g., "mobile_manipulator", "humanoid", "quadruped", etc.)
        type: "mobile_manipulator"
        parts:
          - head
          - manipulator
          - end_effector
          - mobile_base
          # - legs
        head:
          joint_names:
            - "head_pan"
            - "head_tilt"
        manipulator:
          joint_names:
            - "arm_joint_1"
            - "arm_joint_2"
            - "arm_joint_3"
            - "arm_joint_4"
            - "arm_joint_5"
            - "arm_joint_6"
        end_effector:
          joint_names:
            - "gripper"
        mobile_base:
          joint_names:
            - "base_wheel_left"
            - "base_wheel_right"
        # legs:
        #   joint_names:
        #     - ""
      # List of sensors on the robot
      sensors:
        types:
          - rgbd # color and depth camera
          - lidar # light detection and ranging sensor
          - imu # inertial measurement unit
          - camera # regular camera
          - depth_camera # depth camera without color
          - fish_eye # fisheye camera
        rgbd:
          names: ["head_camera", "hand_camera"]
          models: ["realsense_d435", "realsense_d455"]
        lidar:
          names: ["lidar_front"]
          models: ["unk"]
        imu:
          names: [""]
          models: [""]
        camera:
          names: [""]
          models: [""]
        depth_camera:
          names: [""]
          models: [""]
        fish_eye:
          names: ["camera_front", "camera_rear"]
          models: ["unk", "unk"]

    # User information for contact
    user_info:
      # Name of the user
      name: ""
      # Location of the user
      location: ""
      # Contact email for the user
      email: ""

    # ROS bag recording configuration
    rosbag_config:
      # Path to the directory where the recorded bag files will be saved
      record_directory: "/path/to/recorded_bags"
      # List of topics to record (cameras, joint_states, tf, sensors, etc.)
      topics_to_record:
        - "/camera/image_raw"
        - "/camera/camera_info"
      # List of services to record (if any)
      services_to_record:
        - "/camera/get_image"
      # List of actions to record (if any)
      actions_to_record:
        - "/robot/move_base"
      # Duration of each recording in seconds (set to 0 for continuous recording)
      recording_duration: 0
      # Format for the recorded bag files (e.g., "mcap", "sqlite3")
      conversion_format: "mcap" 
      # Whether to compress the output bag files
      compress_output: false
      # If compression is enabled, specify the compression format ("zstd" is the only supported compression format)
      compression_format: "zstd"
      # Specify the compression mode ("file", "message")
      compression_mode: "file"
      # We will try to use a custom storage configuration file if available
      storage_config_file: "/path/to/storage_config.yaml"

    # Control settings for the gamepad
    gamepad_config:
      # Gamepad type (e.g., "dualshock4", "keyboard")
      name: "dualshock4"
      # Mapping of gamepad buttons to actions
      dualshock4:
        button_mapping: # TODO: Check if this is the correct mapping for your gamepad
          record: 8
          pause: 8
          resume: 8
          save: 7
          delete: 6
      keyboard:
        button_mapping:
          record: "r"
          pause: "r"
          resume: "r"
          save: "s"
          delete: "d"
