/**:
  ros__parameters:
    # Robot information
    robot_info:
      # Name of the robot
      name: "sobit_light"
      # Version of the robot
      version: "1.0.0"
      # Description of the robot
      morphology:
        # Type of the robot (e.g., "mobile_manipulator", "humanoid", "quadruped", etc.)
        type: "mobile_manipulator"
        parts:
          - head
          - manipulator
          - end_effector
          - mobile_base
        head:
          joint_names:
            - "head_pan"
            - "head_tilt"
        manipulator:
          joint_names:
            - "arm_joint_1"
            - "arm_joint_2"
            - "arm_joint_3"
            - "arm_joint_4"
            - "arm_joint_5"
            - "arm_joint_6"
        end_effector:
          joint_names:
            - "gripper"
        mobile_base:
          joint_names:
            - "base_wheel_left"
            - "base_wheel_right"
      # List of sensors on the robot
      sensors:
        types:
          - rgbd # color and depth camera
          - lidar # light detection and ranging sensor
          - fish_eye # fisheye camera
        rgbd:
          names: ["head_camera", "hand_camera"]
          models: ["realsense_d435", "realsense_d455"]
        lidar:
          names: ["lidar_front"]
          models: ["unk"]
        fish_eye:
          names: ["camera_front", "camera_rear"]
          models: ["unk", "unk"]

    # User information for contact
    user_info:
      # Name of the user
      name: ""
      # Location of the user
      location: ""
      # Contact email for the user
      email: ""

    # ROS bag recording configuration
    rosbag_config:
      # Path to the directory where the recorded bag files will be saved
      record_directory: "~/vla_ros_bags"
      # List of topics to record (cameras, joint_states, tf, sensors, etc.)
      topics_to_record:
        - /sobit_light/back_camera/camera_info
        - /sobit_light/back_camera/image_raw
        - /sobit_light/back_camera/image_raw/camera_info
        - /sobit_light/back_camera/image_raw/compressed
        - /sobit_light/front_camera/camera_info
        - /sobit_light/front_camera/image_raw
        - /sobit_light/front_camera/image_raw/camera_info
        - /sobit_light/front_camera/image_raw/compressed
        - /sobit_light/lidar/scan
        - /sobit_light/manual_control/cmd_vel
        - /sobit_light/odometry/odometry
        - /sobit_light/tof_camera/camera_info
        - /sobit_light/tof_camera/image_raw
        - /sobit_light/tof_camera/image_raw/camera_info
        - /sobit_light/tof_camera/image_raw/compressedDepth
        - /sobit_light/wheel_odometry/wheel_odometry
        - /sobit_light/joint_states
        - /sobit_light/arm_controller/arm_joint_states
        - /tf
        - /tf_static
      # List of services to record (TODO: not available until ROS 2 Jazzy)
      services_to_record:
        - ""
      # List of actions to record (TODO: not available until ROS 2 Kilted)
      actions_to_record:
        - ""
      # Format for the recorded bag files (e.g., "mcap", "sqlite3")
      conversion_format: "mcap"
      # Specify the compression mode ("none", "file", "message")
      compression_mode: "none"
      # If compression is enabled, specify the compression format ("zstd" is the only supported compression format)
      compression_format: "zstd"

    # Control settings for the gamepad
    gamepad_config:
      # Gamepad type (e.g., "dualshock4", "keyboard")
      name: "dualshock4"
      # Mapping of gamepad buttons to actions
      dualshock4:
        button_mapping:
          record: 7 # Top
          save:   6 # Left
          delete: 6 # Right
      keyboard:
        button_mapping:
          record: "r"
          save: "s"
          delete: "d"
