/**:
  ros__parameters:
    # Directory where the rosbags are stored
    # If left empty (""), it defaults to the `rosbags` folder of `sobits_vla_rosbag_collection`.
    rosbag_directory: ""

    # Path to the recorded bags metadata yaml.
    # If left empty (""), it defaults to `recorded_bags_meta.yaml` inside the resolved `rosbag_directory`.
    recorded_bags_meta_file: ""

    # HuggingFace repository ID or local dataset directory name
    dataset_name: "MyDataset"
